# Generated by Django 4.2.30 on 2026-10-03 10:55

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testing', '0007_historicaltestresult_specs_testresult_specs'),
        ('samples', '0010_alter_historicalsample_sample_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAssignedTest',
            fields=[
            ],
            options={
                'verbose_name': 'My Assigned Test',
                'verbose_name_plural': 'My Assigned Tests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('testing.testresult',),
        ),
        migrations.CreateModel(
            name='PendingApproval',
            fields=[
            ],
            options={
                'verbose_name': 'Pending QCM Approval',
                'verbose_name_plural': 'Pending QCM Approvals',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('samples.sample',),
        ),
        migrations.CreateModel(
            name='PendingVerification',
            fields=[
            ],
            options={
                'verbose_name': 'Pending AQCM Review',
                'verbose_name_plural': 'Pending AQCM Reviews',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('samples.sample',),
        ),
    ]
