# Generated by Django 4.2.30 on 2026-10-03 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_alter_customerfeedback_options_and_more'),
        ('resources', '0025_alter_comparativestatement_options_and_more'),
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingAuditApproval',
            fields=[
            ],
            options={
                'verbose_name': 'Pending QCM Approval (Audits)',
                'verbose_name_plural': 'Pending QCM Approvals (Audits)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('management.internalaudit',),
        ),
        migrations.CreateModel(
            name='PendingCompetencyApproval',
            fields=[
            ],
            options={
                'verbose_name': 'Pending QCM Approval (Competency)',
                'verbose_name_plural': 'Pending QCM Approvals (Competency)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('resources.competencyrecord',),
        ),
        migrations.CreateModel(
            name='PendingDocumentApproval',
            fields=[
            ],
            options={
                'verbose_name': 'Pending QCM Approval (Documents)',
                'verbose_name_plural': 'Pending QCM Approvals (Documents)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('management.document',),
        ),
        migrations.CreateModel(
            name='PendingNCApproval',
            fields=[
            ],
            options={
                'verbose_name': 'Pending QCM Approval (Non-Conformances)',
                'verbose_name_plural': 'Pending QCM Approvals (Non-Conformances)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('management.nonconformance',),
        ),
        migrations.CreateModel(
            name='PendingPRApproval',
            fields=[
            ],
            options={
                'verbose_name': 'Pending QCM Approval (Purchase Requests)',
                'verbose_name_plural': 'Pending QCM Approvals (Purchase Requests)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('resources.purchaserequest',),
        ),
        migrations.CreateModel(
            name='PendingSupplierApproval',
            fields=[
            ],
            options={
                'verbose_name': 'Pending QCM Approval (Suppliers)',
                'verbose_name_plural': 'Pending QCM Approvals (Suppliers)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('resources.supplier',),
        ),
    ]
