# Generated by Django 4.2.30 on 2026-09-29 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testing', '0004_alter_testresult_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NonConformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nc_id', models.CharField(help_text='e.g., NC-2026-001', max_length=50, unique=True)),
                ('date_identified', models.DateField(auto_now_add=True)),
                ('description', models.TextField(help_text='Detailed description of the non-conforming work or issue')),
                ('root_cause_analysis', models.TextField(blank=True, help_text='Why did this happen? (e.g., 5 Whys)', null=True)),
                ('corrective_action', models.TextField(blank=True, help_text='Action taken to eliminate the cause', null=True)),
                ('preventive_action', models.TextField(blank=True, help_text='Action taken to prevent recurrence', null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open - Investigation Pending'), ('INVESTIGATING', 'Under Investigation (RCA)'), ('CAPA_IMPLEMENTED', 'CAPA Implemented - Monitoring'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='closed_ncs', to=settings.AUTH_USER_MODEL)),
                ('identified_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='identified_ncs', to=settings.AUTH_USER_MODEL)),
                ('related_test', models.ForeignKey(blank=True, help_text='Link to specific test result if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, to='testing.testresult')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(help_text='e.g., SOP-CHEM-01', max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('doc_type', models.CharField(choices=[('SOP', 'Standard Operating Procedure'), ('POLICY', 'Quality Policy'), ('FORM', 'Form / Template'), ('MANUAL', 'Quality Manual')], default='SOP', max_length=20)),
                ('version', models.CharField(help_text='e.g., v1.0', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft (Under Review)'), ('ACTIVE', 'Active / Approved for Use'), ('OBSOLETE', 'Obsolete (Do Not Use)')], default='DRAFT', max_length=20)),
                ('file', models.FileField(help_text='Upload PDF version of the document', upload_to='documents/')),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('next_review_date', models.DateField(blank=True, help_text='ISO 17025 requires periodic review of documents', null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approved_docs', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='authored_docs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
