# Generated by Django 4.2.30 on 2026-09-29 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(help_text='e.g., CoA-FERT-0001', max_length=100)),
                ('record_type', models.CharField(default='Certificate of Analysis', max_length=50)),
                ('file', models.FileField(upload_to='archives/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retention_date', models.DateField(help_text='Date until which this record must be retained (e.g., 5 years)')),
                ('archived_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
