# Generated by Django 4.2.30 on 2026-09-30 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_historicaltestresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0002_recordarchive'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRecordArchive',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('record_id', models.CharField(help_text='e.g., CoA-FERT-0001', max_length=100)),
                ('record_type', models.CharField(default='Certificate of Analysis', max_length=50)),
                ('file', models.TextField(max_length=100)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('retention_date', models.DateField(help_text='Date until which this record must be retained (e.g., 5 years)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('archived_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical record archive',
                'verbose_name_plural': 'historical record archives',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalNonConformance',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nc_id', models.CharField(db_index=True, help_text='e.g., NC-2026-001', max_length=50)),
                ('date_identified', models.DateField(blank=True, editable=False)),
                ('description', models.TextField(help_text='Detailed description of the non-conforming work or issue')),
                ('root_cause_analysis', models.TextField(blank=True, help_text='Why did this happen? (e.g., 5 Whys)', null=True)),
                ('corrective_action', models.TextField(blank=True, help_text='Action taken to eliminate the cause', null=True)),
                ('preventive_action', models.TextField(blank=True, help_text='Action taken to prevent recurrence', null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open - Investigation Pending'), ('INVESTIGATING', 'Under Investigation (RCA)'), ('CAPA_IMPLEMENTED', 'CAPA Implemented - Monitoring'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('closed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('identified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('related_test', models.ForeignKey(blank=True, db_constraint=False, help_text='Link to specific test result if applicable', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='testing.testresult')),
            ],
            options={
                'verbose_name': 'historical non conformance',
                'verbose_name_plural': 'historical non conformances',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDocument',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('document_id', models.CharField(db_index=True, help_text='e.g., SOP-CHEM-01', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('doc_type', models.CharField(choices=[('SOP', 'Standard Operating Procedure'), ('POLICY', 'Quality Policy'), ('FORM', 'Form / Template'), ('MANUAL', 'Quality Manual')], default='SOP', max_length=20)),
                ('version', models.CharField(help_text='e.g., v1.0', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft (Under Review)'), ('ACTIVE', 'Active / Approved for Use'), ('OBSOLETE', 'Obsolete (Do Not Use)')], default='DRAFT', max_length=20)),
                ('file', models.TextField(help_text='Upload PDF version of the document', max_length=100)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('next_review_date', models.DateField(blank=True, help_text='ISO 17025 requires periodic review of documents', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical document',
                'verbose_name_plural': 'historical documents',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
