# Generated by Django 4.2.30 on 2026-09-30 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0003_historicalrecordarchive_historicalnonconformance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_id', models.CharField(help_text='e.g., AUDIT-2026-01', max_length=50, unique=True)),
                ('scope', models.CharField(help_text='e.g., Chemistry Lab Methods & Equipment', max_length=255)),
                ('scheduled_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='SCHEDULED', max_length=20)),
                ('summary_report', models.TextField(blank=True, null=True)),
                ('lead_auditor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalInternalAudit',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('audit_id', models.CharField(db_index=True, help_text='e.g., AUDIT-2026-01', max_length=50)),
                ('scope', models.CharField(help_text='e.g., Chemistry Lab Methods & Equipment', max_length=255)),
                ('scheduled_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='SCHEDULED', max_length=20)),
                ('summary_report', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lead_auditor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical internal audit',
                'verbose_name_plural': 'historical internal audits',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAuditFinding',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('OBSERVATION', 'Observation'), ('MINOR', 'Minor Non-Conformance'), ('MAJOR', 'Major Non-Conformance')], max_length=20)),
                ('clause_reference', models.CharField(blank=True, help_text='e.g., ISO 17025: 6.4.2', max_length=50, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('audit', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='management.internalaudit')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('linked_nc', models.ForeignKey(blank=True, db_constraint=False, help_text='Linked CAPA for this finding.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='management.nonconformance')),
            ],
            options={
                'verbose_name': 'historical audit finding',
                'verbose_name_plural': 'historical audit findings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='AuditFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('OBSERVATION', 'Observation'), ('MINOR', 'Minor Non-Conformance'), ('MAJOR', 'Major Non-Conformance')], max_length=20)),
                ('clause_reference', models.CharField(blank=True, help_text='e.g., ISO 17025: 6.4.2', max_length=50, null=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='management.internalaudit')),
                ('linked_nc', models.OneToOneField(blank=True, help_text='Linked CAPA for this finding.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.nonconformance')),
            ],
        ),
    ]
