# Generated by Django 4.2.30 on 2026-09-30 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0004_internalaudit_historicalinternalaudit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('risk_type', models.CharField(choices=[('RISK', 'Risk (Threat)'), ('OPPORTUNITY', 'Opportunity')], default='RISK', max_length=20)),
                ('likelihood', models.PositiveIntegerField(default=3, help_text='1 (Rare) to 5 (Almost Certain)')),
                ('impact', models.PositiveIntegerField(default=3, help_text='1 (Negligible) to 5 (Severe)')),
                ('mitigation_plan', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open/Active'), ('MITIGATED', 'Mitigated/Closed')], default='OPEN', max_length=20)),
                ('date_identified', models.DateField(auto_now_add=True)),
                ('identified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManagementReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField()),
                ('attendees_list', models.TextField(help_text='List of management attendees')),
                ('inputs_discussion', models.TextField(help_text='Discussion on internal/external changes, customer feedback, previous action items, etc.')),
                ('outputs_and_decisions', models.TextField(blank=True, help_text='Decisions related to QMS effectiveness, resources needed, and improvement actions.', null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed')], default='SCHEDULED', max_length=20)),
                ('chairperson', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalRisk',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('risk_type', models.CharField(choices=[('RISK', 'Risk (Threat)'), ('OPPORTUNITY', 'Opportunity')], default='RISK', max_length=20)),
                ('likelihood', models.PositiveIntegerField(default=3, help_text='1 (Rare) to 5 (Almost Certain)')),
                ('impact', models.PositiveIntegerField(default=3, help_text='1 (Negligible) to 5 (Severe)')),
                ('mitigation_plan', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open/Active'), ('MITIGATED', 'Mitigated/Closed')], default='OPEN', max_length=20)),
                ('date_identified', models.DateField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('identified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical risk',
                'verbose_name_plural': 'historical risks',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalManagementReview',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('meeting_date', models.DateField()),
                ('attendees_list', models.TextField(help_text='List of management attendees')),
                ('inputs_discussion', models.TextField(help_text='Discussion on internal/external changes, customer feedback, previous action items, etc.')),
                ('outputs_and_decisions', models.TextField(blank=True, help_text='Decisions related to QMS effectiveness, resources needed, and improvement actions.', null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed')], default='SCHEDULED', max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('chairperson', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical management review',
                'verbose_name_plural': 'historical management reviews',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
