# Generated by Django 4.2.30 on 2026-09-30 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_risk_managementreview_historicalrisk_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditfinding',
            options={'verbose_name': 'AuditFinding (QCL-FRM-10.09)', 'verbose_name_plural': 'AuditFindings (QCL-FRM-10.09)'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Document (QCL-FRM-7.01)', 'verbose_name_plural': 'Documents (QCL-FRM-7.01)'},
        ),
        migrations.AlterModelOptions(
            name='historicalauditfinding',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical AuditFinding (QCL-FRM-10.09)', 'verbose_name_plural': 'historical AuditFindings (QCL-FRM-10.09)'},
        ),
        migrations.AlterModelOptions(
            name='historicaldocument',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Document (QCL-FRM-7.01)', 'verbose_name_plural': 'historical Documents (QCL-FRM-7.01)'},
        ),
        migrations.AlterModelOptions(
            name='historicalinternalaudit',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical InternalAudit (QCL-FRM-10.10)', 'verbose_name_plural': 'historical InternalAudits (QCL-FRM-10.10)'},
        ),
        migrations.AlterModelOptions(
            name='historicalnonconformance',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical NonConformance (QCL-FRM-14.01)', 'verbose_name_plural': 'historical NonConformances (QCL-FRM-14.01)'},
        ),
        migrations.AlterModelOptions(
            name='historicalrisk',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Risk (QCL-FRM-8.01)', 'verbose_name_plural': 'historical Risks (QCL-FRM-8.01)'},
        ),
        migrations.AlterModelOptions(
            name='internalaudit',
            options={'verbose_name': 'InternalAudit (QCL-FRM-10.10)', 'verbose_name_plural': 'InternalAudits (QCL-FRM-10.10)'},
        ),
        migrations.AlterModelOptions(
            name='nonconformance',
            options={'verbose_name': 'NonConformance (QCL-FRM-14.01)', 'verbose_name_plural': 'NonConformances (QCL-FRM-14.01)'},
        ),
        migrations.AlterModelOptions(
            name='risk',
            options={'verbose_name': 'Risk (QCL-FRM-8.01)', 'verbose_name_plural': 'Risks (QCL-FRM-8.01)'},
        ),
    ]
