# Generated by Django 4.2.30 on 2026-09-30 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0006_alter_auditfinding_options_alter_document_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnonconformance',
            name='acceptance_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalnonconformance',
            name='evaluated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='QCM', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalnonconformance',
            name='halt_work',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalnonconformance',
            name='impact_on_previous_result',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalnonconformance',
            name='level_of_risk',
            field=models.CharField(choices=[('VERY_LOW', 'Very Low'), ('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('VERY_HIGH', 'Very High')], default='MODERATE', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalnonconformance',
            name='nc_type',
            field=models.CharField(choices=[('ESSENTIAL', 'Essential'), ('MINOR', 'Minor Non-Essential')], default='ESSENTIAL', max_length=30),
        ),
        migrations.AddField(
            model_name='historicalnonconformance',
            name='recall_work',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalnonconformance',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='AQCM', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalnonconformance',
            name='source',
            field=models.CharField(choices=[('AUDIT', 'Audit NC'), ('LAB', 'Laboratory Activities'), ('SUGGESTION', 'Suggestion'), ('PT_ILC', 'PT/ILC'), ('COMPLAINT', 'Complaint'), ('FEEDBACK', 'Customer Feedback'), ('RISK', 'Risk Assessment'), ('OTHER', 'Any Other')], default='LAB', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalnonconformance',
            name='withhold_reports',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nonconformance',
            name='acceptance_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='nonconformance',
            name='evaluated_by',
            field=models.ForeignKey(blank=True, help_text='QCM', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_ncs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nonconformance',
            name='halt_work',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nonconformance',
            name='impact_on_previous_result',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nonconformance',
            name='level_of_risk',
            field=models.CharField(choices=[('VERY_LOW', 'Very Low'), ('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('VERY_HIGH', 'Very High')], default='MODERATE', max_length=20),
        ),
        migrations.AddField(
            model_name='nonconformance',
            name='nc_type',
            field=models.CharField(choices=[('ESSENTIAL', 'Essential'), ('MINOR', 'Minor Non-Essential')], default='ESSENTIAL', max_length=30),
        ),
        migrations.AddField(
            model_name='nonconformance',
            name='recall_work',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nonconformance',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='AQCM', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ncs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nonconformance',
            name='source',
            field=models.CharField(choices=[('AUDIT', 'Audit NC'), ('LAB', 'Laboratory Activities'), ('SUGGESTION', 'Suggestion'), ('PT_ILC', 'PT/ILC'), ('COMPLAINT', 'Complaint'), ('FEEDBACK', 'Customer Feedback'), ('RISK', 'Risk Assessment'), ('OTHER', 'Any Other')], default='LAB', max_length=20),
        ),
        migrations.AddField(
            model_name='nonconformance',
            name='withhold_reports',
            field=models.BooleanField(default=False),
        ),
    ]
