# Generated by Django 4.2.30 on 2026-10-02 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0007_historicalnonconformance_acceptance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnonconformance',
            name='rca_carried_out_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalnonconformance',
            name='rca_machine',
            field=models.TextField(blank=True, null=True, verbose_name='Machine / Equipment'),
        ),
        migrations.AddField(
            model_name='historicalnonconformance',
            name='rca_man',
            field=models.TextField(blank=True, null=True, verbose_name='Man / Personnel'),
        ),
        migrations.AddField(
            model_name='historicalnonconformance',
            name='rca_material',
            field=models.TextField(blank=True, null=True, verbose_name='Material / Environment'),
        ),
        migrations.AddField(
            model_name='historicalnonconformance',
            name='rca_method',
            field=models.TextField(blank=True, null=True, verbose_name='Method / Procedure'),
        ),
        migrations.AddField(
            model_name='historicalnonconformance',
            name='similar_non_conformance',
            field=models.BooleanField(default=False, verbose_name='Similar Non-Conformance exist?'),
        ),
        migrations.AddField(
            model_name='nonconformance',
            name='rca_carried_out_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rca_carried_out', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nonconformance',
            name='rca_machine',
            field=models.TextField(blank=True, null=True, verbose_name='Machine / Equipment'),
        ),
        migrations.AddField(
            model_name='nonconformance',
            name='rca_man',
            field=models.TextField(blank=True, null=True, verbose_name='Man / Personnel'),
        ),
        migrations.AddField(
            model_name='nonconformance',
            name='rca_material',
            field=models.TextField(blank=True, null=True, verbose_name='Material / Environment'),
        ),
        migrations.AddField(
            model_name='nonconformance',
            name='rca_method',
            field=models.TextField(blank=True, null=True, verbose_name='Method / Procedure'),
        ),
        migrations.AddField(
            model_name='nonconformance',
            name='similar_non_conformance',
            field=models.BooleanField(default=False, verbose_name='Similar Non-Conformance exist?'),
        ),
        migrations.AlterField(
            model_name='historicalnonconformance',
            name='root_cause_analysis',
            field=models.TextField(blank=True, help_text='General RCA / Summary', null=True),
        ),
        migrations.AlterField(
            model_name='nonconformance',
            name='root_cause_analysis',
            field=models.TextField(blank=True, help_text='General RCA / Summary', null=True),
        ),
    ]
