# Generated by Django 4.2.30 on 2026-10-02 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0008_historicalnonconformance_rca_carried_out_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('q1_delivery_time', models.IntegerField(choices=[(4, 'Excellent A+ (4)'), (3, 'V. Good A (3)'), (2, 'Good B (2)'), (1, 'Poor C (1)')], default=4, verbose_name='1. How do you estimate time of delivery of our laboratory reports?')),
                ('q2_politeness', models.IntegerField(choices=[(4, 'Excellent A+ (4)'), (3, 'V. Good A (3)'), (2, 'Good B (2)'), (1, 'Poor C (1)')], default=4, verbose_name='2. How do you estimate politeness of our laboratory staff?')),
                ('q3_accuracy', models.IntegerField(choices=[(4, 'Excellent A+ (4)'), (3, 'V. Good A (3)'), (2, 'Good B (2)'), (1, 'Poor C (1)')], default=4, verbose_name='3. How do you estimate accuracy of contents of our Laboratory reports?')),
                ('q4_response', models.IntegerField(choices=[(4, 'Excellent A+ (4)'), (3, 'V. Good A (3)'), (2, 'Good B (2)'), (1, 'Poor C (1)')], default=4, verbose_name='4. How do you rate our response to your complaints & feedbacks?')),
                ('q5_satisfaction', models.IntegerField(choices=[(4, 'Excellent A+ (4)'), (3, 'V. Good A (3)'), (2, 'Good B (2)'), (1, 'Poor C (1)')], default=4, verbose_name='5. Rating of your overall satisfaction level?')),
                ('q6_knowledge', models.IntegerField(choices=[(4, 'Excellent A+ (4)'), (3, 'V. Good A (3)'), (2, 'Good B (2)'), (1, 'Poor C (1)')], default=4, verbose_name='6. How do you estimate knowledge of our laboratory analyst?')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Any specific comments / complaint / suggestion or feedback you would like to add:')),
            ],
        ),
        migrations.CreateModel(
            name='LabCleaningInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_area', models.CharField(help_text='e.g. Sample Prep Room', max_length=150)),
                ('month_year', models.CharField(help_text='e.g. October 2026', max_length=50)),
                ('lights_acs_cleaned', models.BooleanField(default=False, verbose_name="Cleaning Of Lights and AC's (Monthly)")),
                ('overall_spray', models.BooleanField(default=False, verbose_name='Overall Cleaning and Spray in Lab (Monthly)')),
                ('racks_cabinets', models.BooleanField(default=False, verbose_name='Cleaning of Racks, Cabinets and Fumehood (Weekly)')),
            ],
        ),
        migrations.CreateModel(
            name='MasterListFileFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_code', models.CharField(max_length=100, verbose_name='File code')),
                ('title', models.CharField(max_length=200, verbose_name='Title of File/Folder/Register')),
                ('volume', models.CharField(max_length=50, verbose_name='Volume')),
                ('keeper', models.CharField(max_length=100, verbose_name='Keeper')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='MasterListRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Record Title')),
                ('code', models.CharField(max_length=100, verbose_name='Record Code')),
                ('revision_no', models.CharField(max_length=50, verbose_name='Revision No.')),
                ('file_code', models.CharField(max_length=100, verbose_name='File code')),
                ('location', models.CharField(max_length=200, verbose_name='File Location')),
                ('retention_period', models.CharField(max_length=100, verbose_name='Retention Period')),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabCleaningDailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('floor_sinks_taps', models.BooleanField(default=False, verbose_name='Floor, Sanitary Sinks and Taps')),
                ('bench_top_shelves', models.BooleanField(default=False, verbose_name='Bench Top/Shelves')),
                ('equipment', models.BooleanField(default=False, verbose_name='Equipment')),
                ('checked_by', models.CharField(blank=True, max_length=50, null=True)),
                ('verified_by', models.CharField(blank=True, max_length=50, null=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_records', to='management.labcleaninginspection')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalMasterListRecord',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Record Title')),
                ('code', models.CharField(max_length=100, verbose_name='Record Code')),
                ('revision_no', models.CharField(max_length=50, verbose_name='Revision No.')),
                ('file_code', models.CharField(max_length=100, verbose_name='File code')),
                ('location', models.CharField(max_length=200, verbose_name='File Location')),
                ('retention_period', models.CharField(max_length=100, verbose_name='Retention Period')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical master list record',
                'verbose_name_plural': 'historical master list records',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMasterListFileFolder',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('file_code', models.CharField(max_length=100, verbose_name='File code')),
                ('title', models.CharField(max_length=200, verbose_name='Title of File/Folder/Register')),
                ('volume', models.CharField(max_length=50, verbose_name='Volume')),
                ('keeper', models.CharField(max_length=100, verbose_name='Keeper')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical master list file folder',
                'verbose_name_plural': 'historical master list file folders',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLabCleaningInspection',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('section_area', models.CharField(help_text='e.g. Sample Prep Room', max_length=150)),
                ('month_year', models.CharField(help_text='e.g. October 2026', max_length=50)),
                ('lights_acs_cleaned', models.BooleanField(default=False, verbose_name="Cleaning Of Lights and AC's (Monthly)")),
                ('overall_spray', models.BooleanField(default=False, verbose_name='Overall Cleaning and Spray in Lab (Monthly)')),
                ('racks_cabinets', models.BooleanField(default=False, verbose_name='Cleaning of Racks, Cabinets and Fumehood (Weekly)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical lab cleaning inspection',
                'verbose_name_plural': 'historical lab cleaning inspections',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCustomerFeedback',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, editable=False)),
                ('q1_delivery_time', models.IntegerField(choices=[(4, 'Excellent A+ (4)'), (3, 'V. Good A (3)'), (2, 'Good B (2)'), (1, 'Poor C (1)')], default=4, verbose_name='1. How do you estimate time of delivery of our laboratory reports?')),
                ('q2_politeness', models.IntegerField(choices=[(4, 'Excellent A+ (4)'), (3, 'V. Good A (3)'), (2, 'Good B (2)'), (1, 'Poor C (1)')], default=4, verbose_name='2. How do you estimate politeness of our laboratory staff?')),
                ('q3_accuracy', models.IntegerField(choices=[(4, 'Excellent A+ (4)'), (3, 'V. Good A (3)'), (2, 'Good B (2)'), (1, 'Poor C (1)')], default=4, verbose_name='3. How do you estimate accuracy of contents of our Laboratory reports?')),
                ('q4_response', models.IntegerField(choices=[(4, 'Excellent A+ (4)'), (3, 'V. Good A (3)'), (2, 'Good B (2)'), (1, 'Poor C (1)')], default=4, verbose_name='4. How do you rate our response to your complaints & feedbacks?')),
                ('q5_satisfaction', models.IntegerField(choices=[(4, 'Excellent A+ (4)'), (3, 'V. Good A (3)'), (2, 'Good B (2)'), (1, 'Poor C (1)')], default=4, verbose_name='5. Rating of your overall satisfaction level?')),
                ('q6_knowledge', models.IntegerField(choices=[(4, 'Excellent A+ (4)'), (3, 'V. Good A (3)'), (2, 'Good B (2)'), (1, 'Poor C (1)')], default=4, verbose_name='6. How do you estimate knowledge of our laboratory analyst?')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Any specific comments / complaint / suggestion or feedback you would like to add:')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical customer feedback',
                'verbose_name_plural': 'historical customer feedbacks',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
