# Generated by Django 4.2.30 on 2026-10-03 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_labcleaninginspection_update_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerfeedback',
            options={'verbose_name': 'Customer Feedback (QCL-FRM-21.01)', 'verbose_name_plural': 'Customer Feedback (QCL-FRM-21.01)s'},
        ),
        migrations.AlterModelOptions(
            name='historicalcustomerfeedback',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Customer Feedback (QCL-FRM-21.01)', 'verbose_name_plural': 'historical Customer Feedback (QCL-FRM-21.01)s'},
        ),
        migrations.AlterModelOptions(
            name='historicallabcleaninginspection',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Lab Cleaning Inspection (QCL-FRM-17.14)', 'verbose_name_plural': 'historical Lab Cleaning Inspection (QCL-FRM-17.14)s'},
        ),
        migrations.AlterModelOptions(
            name='historicalmanagementreview',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Management Review (QCL-FRM-9.01)', 'verbose_name_plural': 'historical Management Review (QCL-FRM-9.01)s'},
        ),
        migrations.AlterModelOptions(
            name='historicalmasterlistfilefolder',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Master List of Files (QCL-FRM-20.02)', 'verbose_name_plural': 'historical Master List of Files (QCL-FRM-20.02)s'},
        ),
        migrations.AlterModelOptions(
            name='historicalmasterlistrecord',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Master List of Records (QCL-FRM-20.01)', 'verbose_name_plural': 'historical Master List of Records (QCL-FRM-20.01)s'},
        ),
        migrations.AlterModelOptions(
            name='labcleaninginspection',
            options={'verbose_name': 'Lab Cleaning Inspection (QCL-FRM-17.14)', 'verbose_name_plural': 'Lab Cleaning Inspection (QCL-FRM-17.14)s'},
        ),
        migrations.AlterModelOptions(
            name='managementreview',
            options={'verbose_name': 'Management Review (QCL-FRM-9.01)', 'verbose_name_plural': 'Management Review (QCL-FRM-9.01)s'},
        ),
        migrations.AlterModelOptions(
            name='masterlistfilefolder',
            options={'verbose_name': 'Master List of Files (QCL-FRM-20.02)', 'verbose_name_plural': 'Master List of Files (QCL-FRM-20.02)s'},
        ),
        migrations.AlterModelOptions(
            name='masterlistrecord',
            options={'verbose_name': 'Master List of Records (QCL-FRM-20.01)', 'verbose_name_plural': 'Master List of Records (QCL-FRM-20.01)s'},
        ),
    ]
