# Generated by Django 4.2.30 on 2026-10-07 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0012_alter_customerfeedback_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISODocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('LSP', 'Laboratory Standard Procedure (LSP)'), ('FRM', 'Form (FRM)'), ('POL', 'Policy (POL)'), ('MAN', 'Manual (LSM)'), ('OTHER', 'Other')], default='LSP', max_length=10)),
                ('document_code', models.CharField(help_text='e.g., QCL-LSP-01', max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('revision_number', models.CharField(default='00', max_length=20)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='iso_documents/')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('OBSOLETE', 'Obsolete')], default='ACTIVE', max_length=20)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iso_docs_approved', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iso_docs_prepared', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iso_docs_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ISO Document (LSP/POL/FRM)',
                'verbose_name_plural': 'ISO Documents Database',
                'ordering': ['doc_type', 'document_code'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalISODocument',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('LSP', 'Laboratory Standard Procedure (LSP)'), ('FRM', 'Form (FRM)'), ('POL', 'Policy (POL)'), ('MAN', 'Manual (LSM)'), ('OTHER', 'Other')], default='LSP', max_length=10)),
                ('document_code', models.CharField(db_index=True, help_text='e.g., QCL-LSP-01', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('revision_number', models.CharField(default='00', max_length=20)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('file', models.TextField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('OBSOLETE', 'Obsolete')], default='ACTIVE', max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical ISO Document (LSP/POL/FRM)',
                'verbose_name_plural': 'historical ISO Documents Database',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
