# Generated by Django 4.2.30 on 2026-10-07 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_isodocument_historicalisodocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObsoleteDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_code', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('revision_number', models.CharField(max_length=20)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='iso_documents/')),
                ('obsolete_date', models.DateTimeField(auto_now_add=True)),
                ('original_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.isodocument')),
            ],
            options={
                'verbose_name': 'Obsolete Document',
                'verbose_name_plural': 'Obsolete Documents Archive',
            },
        ),
    ]
