# Generated by Django 4.2.30 on 2026-09-29 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Total Nitrogen, Moisture, pH, Biuret', max_length=100)),
                ('default_unit', models.CharField(default='%', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TestMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., AOAC 993.13, ISO 5315, In-House SOP-01', max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_accredited', models.BooleanField(default=True, help_text='Is this method accredited under ISO 17025?')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('unit', models.CharField(default='%', max_length=50)),
                ('measurement_uncertainty', models.DecimalField(blank=True, decimal_places=4, help_text='e.g., 0.05 (will be reported as ± 0.05)', max_digits=10, null=True)),
                ('tested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for Review'), ('APPROVED', 'Approved (Verified)'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, help_text='Deviations from method or QC notes.', null=True)),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tests_performed', to=settings.AUTH_USER_MODEL)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='testing.testmethod')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='testing.parameter')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='samples.sample')),
            ],
            options={
                'unique_together': {('sample', 'parameter')},
            },
        ),
    ]
