# Generated by Django 4.2.30 on 2026-09-29 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='analyst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tests_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='testing.testmethod'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='result_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Analysis (Requested)'), ('DRAFT', 'Draft / In Progress'), ('SUBMITTED', 'Submitted for Review'), ('APPROVED', 'Approved (Verified)'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='tested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='unit',
            field=models.CharField(blank=True, default='%', max_length=50, null=True),
        ),
    ]
