# Generated by Django 4.2.30 on 2026-09-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_reagentstandard'),
        ('testing', '0002_alter_testresult_analyst_alter_testresult_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='equipment_used',
            field=models.ManyToManyField(blank=True, help_text='Equipment used for this specific test', to='resources.equipment'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='reagents_used',
            field=models.ManyToManyField(blank=True, help_text='Standards or reagents used', to='resources.reagentstandard'),
        ),
    ]
