# Generated by Django 4.2.30 on 2026-09-29 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_sample_approved_at_sample_approved_by_and_more'),
        ('testing', '0003_testresult_equipment_used_testresult_reagents_used'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='testresult',
            name='parent_result',
            field=models.ForeignKey(blank=True, help_text='If Duplicate, select the original TestResult', null=True, on_delete=django.db.models.deletion.CASCADE, to='testing.testresult'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='result_type',
            field=models.CharField(choices=[('REGULAR', 'Regular Sample'), ('BLANK', 'Method Blank'), ('DUPLICATE', 'Duplicate'), ('CRM', 'Certified Reference Material (CRM)')], default='REGULAR', max_length=20),
        ),
        migrations.AddField(
            model_name='testresult',
            name='target_value',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Expected value for CRMs', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='sample',
            field=models.ForeignKey(blank=True, help_text='Blank for standalone QC tests', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='samples.sample'),
        ),
    ]
