# Generated by Django 4.2.30 on 2026-09-30 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_historicalsample'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testing', '0004_alter_testresult_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTestResult',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('result_type', models.CharField(choices=[('REGULAR', 'Regular Sample'), ('BLANK', 'Method Blank'), ('DUPLICATE', 'Duplicate'), ('CRM', 'Certified Reference Material (CRM)')], default='REGULAR', max_length=20)),
                ('target_value', models.DecimalField(blank=True, decimal_places=4, help_text='Expected value for CRMs', max_digits=10, null=True)),
                ('result_value', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, default='%', max_length=50, null=True)),
                ('measurement_uncertainty', models.DecimalField(blank=True, decimal_places=4, help_text='e.g., 0.05 (will be reported as ± 0.05)', max_digits=10, null=True)),
                ('tested_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Analysis (Requested)'), ('DRAFT', 'Draft / In Progress'), ('SUBMITTED', 'Submitted for Review'), ('APPROVED', 'Approved (Verified)'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, help_text='Deviations from method or QC notes.', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('analyst', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('method', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='testing.testmethod')),
                ('parameter', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='testing.parameter')),
                ('parent_result', models.ForeignKey(blank=True, db_constraint=False, help_text='If Duplicate, select the original TestResult', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='testing.testresult')),
                ('reviewed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(blank=True, db_constraint=False, help_text='Blank for standalone QC tests', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='samples.sample')),
            ],
            options={
                'verbose_name': 'historical test result',
                'verbose_name_plural': 'historical test results',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
