# Generated by Django 4.2.30 on 2026-09-30 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testing', '0005_historicaltestresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltestresult',
            name='assigned_to',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Analyst assigned to perform this parameter', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testresult',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Analyst assigned to perform this parameter', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicaltestresult',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Assignment'), ('ASSIGNED', 'Assigned to Analyst'), ('IN_PROGRESS', 'In Progress'), ('PENDING_VERIFICATION', 'Pending AQCM Verification'), ('VERIFIED', 'Verified by AQCM')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Assignment'), ('ASSIGNED', 'Assigned to Analyst'), ('IN_PROGRESS', 'In Progress'), ('PENDING_VERIFICATION', 'Pending AQCM Verification'), ('VERIFIED', 'Verified by AQCM')], default='PENDING', max_length=20),
        ),
    ]
