# Generated by Django 4.2.30 on 2026-09-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_historicaltestresult_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltestresult',
            name='specs',
            field=models.CharField(blank=True, help_text='e.g., Min 98%, 10-15 ppm', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='specs',
            field=models.CharField(blank=True, help_text='e.g., Min 98%, 10-15 ppm', max_length=100, null=True),
        ),
    ]
