# Generated by Django 4.2.30 on 2026-10-03 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0007_historicaltestresult_specs_testresult_specs'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAssignedTest',
            fields=[
            ],
            options={
                'verbose_name': 'My Assigned Test',
                'verbose_name_plural': 'My Assigned Tests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('testing.testresult',),
        ),
    ]
