# Generated by Django 4.2.30 on 2026-10-04 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testing', '0007_historicaltestresult_specs_testresult_specs'),
        ('resources', '0026_historicalreagentstandard_current_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostingDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Costing & Financial Reports',
                'verbose_name_plural': 'Costing & Financial Reports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestBOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Notes on this recipe', null=True)),
                ('parameter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bom', to='testing.parameter')),
            ],
            options={
                'verbose_name': 'Test Recipe / BOM',
                'verbose_name_plural': 'Test Recipes / BOMs',
            },
        ),
        migrations.CreateModel(
            name='InventoryIssuance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_issued', models.DecimalField(decimal_places=4, max_digits=10)),
                ('calculated_cost', models.DecimalField(decimal_places=4, editable=False, help_text='Automatically calculated at time of issuance', max_digits=10)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('purpose', models.CharField(blank=True, help_text='e.g. Standard Preparation, Direct Testing', max_length=255, null=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='issuances', to='resources.reagentstandard')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('test_result', models.ForeignKey(blank=True, help_text='The specific test serial number this was issued for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chemical_issuances', to='testing.testresult')),
            ],
            options={
                'verbose_name': 'Chemical/CRM Issuance Log',
                'verbose_name_plural': 'Chemical/CRM Issuance Logs',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.DecimalField(decimal_places=4, help_text='Quantity required per test', max_digits=10)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.testbom')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='resources.reagentstandard')),
            ],
        ),
    ]
