# Generated by Django 4.2.30 on 2026-10-04 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testing', '0007_historicaltestresult_specs_testresult_specs'),
        ('resources', '0025_alter_comparativestatement_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestBOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Notes on this recipe', null=True)),
                ('parameter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bom', to='testing.parameter')),
            ],
            options={
                'verbose_name': 'Test Recipe / BOM',
                'verbose_name_plural': 'Test Recipes / BOMs',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Sulfuric Acid, Sodium Hydroxide', max_length=200)),
                ('item_type', models.CharField(choices=[('CHEMICAL', 'Chemical / Reagent'), ('CRM', 'Certified Reference Material (CRM)'), ('CONSUMABLE', 'Consumable (Filter Paper, etc.)'), ('GLASSWARE', 'Glassware')], default='CHEMICAL', max_length=20)),
                ('part_number', models.CharField(blank=True, help_text='CAS Number, SKU, or Internal ID', max_length=100, null=True)),
                ('unit_of_measure', models.CharField(help_text='e.g. g, mg, kg, ml, L, unit', max_length=20)),
                ('unit_cost', models.DecimalField(decimal_places=4, help_text='Cost per single unit of measure', max_digits=10)),
                ('current_stock', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('reorder_level', models.DecimalField(decimal_places=4, default=0, help_text='Alert if stock falls below this', max_digits=12)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.supplier')),
            ],
            options={
                'verbose_name': 'Inventory Item (Chemical/CRM)',
                'verbose_name_plural': 'Inventory Items (Chemicals/CRMs)',
            },
        ),
        migrations.CreateModel(
            name='InventoryIssuance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_issued', models.DecimalField(decimal_places=4, max_digits=10)),
                ('calculated_cost', models.DecimalField(decimal_places=4, editable=False, help_text='Automatically calculated at time of issuance', max_digits=10)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('purpose', models.CharField(blank=True, help_text='e.g. Standard Preparation, Direct Testing', max_length=255, null=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='issuances', to='inventory.inventoryitem')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('test_result', models.ForeignKey(blank=True, help_text='The specific test serial number this was issued for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chemical_issuances', to='testing.testresult')),
            ],
            options={
                'verbose_name': 'Chemical/CRM Issuance Log',
                'verbose_name_plural': 'Chemical/CRM Issuance Logs',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.DecimalField(decimal_places=4, help_text='Quantity required per test', max_digits=10)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.testbom')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.inventoryitem')),
            ],
        ),
    ]
