# Generated by Django 4.2.30 on 2026-10-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Laboratory KPI Dashboard',
                'verbose_name_plural': 'Laboratory KPI Dashboard',
                'managed': False,
            },
        ),
    ]
