# Generated by Django 4.2.30 on 2026-10-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'On-Demand Filter Reports',
                'verbose_name_plural': 'On-Demand Filter Reports',
                'managed': False,
            },
        ),
    ]
