import os
import dj_database_url
"""
Django settings for lims_core project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*^&^$8_!cb38b!4@ty13-e1y7cscwic(3gq+l)@9v^2dr^m&^x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'inventory',
    'reports',
    'inbox',
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework',
    'corsheaders',
    'simple_history',
    'unfold.contrib.simple_history',

    # Local apps
    'accounts',
    'samples',
    'testing',
    'resources',
    'dashboard',
    'management',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
]

AUTH_USER_MODEL = 'accounts.User'
CORS_ALLOW_ALL_ORIGINS = True # For dev only, should be restricted in prod

ROOT_URLCONF = 'lims_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lims_core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static_assets']

STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = 'dashboard_home'
LOGIN_URL = 'login'
LOGOUT_REDIRECT_URL = 'login'

UNFOLD = {
    "SITE_TITLE": "QC Lab Manager",
    "SITE_HEADER": "ISO 17025 LIMS",
    "SITE_URL": "/",
    
    
    
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "LSP-01: Competence & Auth",
                "separator": True,
                "items": [
                    {"title": "1.01 Authorization Permit", "icon": "verified", "link": "/admin/resources/personnelauthorizationpermit/"},
                    {"title": "1.01C Internal Samples", "icon": "science", "link": "/admin/resources/competencyevalinternalsample/"},
                    {"title": "1.01D PT Samples", "icon": "biotech", "link": "/admin/resources/competencyevalptsample/"},
                    {"title": "1.01E Grading (Equipment)", "icon": "build", "link": "/admin/resources/gradingmatrixequipment/"},
                    {"title": "1.01F Grading (Product)", "icon": "inventory", "link": "/admin/resources/gradingmatrixproduct/"},
                    {"title": "1.01G Grading (Document)", "icon": "description", "link": "/admin/resources/gradingmatrixdocument/"},
                    {"title": "1.02 Authorized Analyst List", "icon": "list_alt", "link": "/admin/resources/authorizedanalystlist/"},
                    {"title": "1.03 Technical Personnel List", "icon": "groups", "link": "/admin/resources/technicalpersonnellist/"},
                    {"title": "1.04 Competency Monitoring", "icon": "monitoring", "link": "/admin/resources/competencymonitoring/"},
                ]
            },
            {
                "title": "LSP-02: Training Management",
                "separator": True,
                "items": [
                    {"title": "2.02 Training Need Assessment", "icon": "assignment", "link": "/admin/resources/trainingneedassessment/"},
                    {"title": "2.03 Annual Training Plan", "icon": "event_note", "link": "/admin/resources/annualtrainingplan/"},
                    {"title": "2.04 Attendance Sheet", "icon": "co_present", "link": "/admin/resources/trainingattendancesheet/"},
                    {"title": "2.05 Training Evaluation", "icon": "grading", "link": "/admin/resources/trainingevaluation/"},
                    {"title": "2.06 Authorized Personnel List", "icon": "recent_actors", "link": "/admin/resources/authorizedpersonnellist_2_06/"},
                    {"title": "2.07 Training Feedback", "icon": "feedback", "link": "/admin/resources/trainingfeedback/"},
                    {"title": "2.08 Individual Training Record", "icon": "person_search", "link": "/admin/resources/individualtrainingrecord/"},
                    {"title": "2.09 Orientation Plan", "icon": "directions", "link": "/admin/resources/orientationplan/"},
                    {"title": "2.10 Competence Reassessment", "icon": "refresh", "link": "/admin/resources/competencereassessment/"},
                    {"title": "2.11 New Induction Orientation", "icon": "emoji_people", "link": "/admin/resources/newinductionorientation_2_11/"},
                    {"title": "2.12 Trainer Evaluation", "icon": "record_voice_over", "link": "/admin/resources/trainerevaluation/"},
                ]
            },
            {
                "title": "LSP-03: Environmental Conditions",
                "separator": True,
                "items": [
                    {"title": "3.01 Environmental Monitoring", "icon": "thermostat", "link": "/admin/resources/environmentalmonitoring_3_01/"},
                    {"title": "3.02 Humidity Control Chart", "icon": "water_drop", "link": "/admin/resources/humiditycontrolchart_3_02/"},
                    {"title": "3.03 Temperature Control Chart", "icon": "ac_unit", "link": "/admin/resources/temperaturecontrolchart_3_03/"},
                ]
            },
            {
                "title": "LSP-04: Equipment Control",
                "separator": True,
                "items": [
                    {"title": "4.01 Corrective Action Request", "icon": "report_problem", "link": "/admin/resources/correctiveactionrequest_4_01/"},
                    {"title": "4.02 Master List of Equipment", "icon": "precision_manufacturing", "link": "/admin/resources/masterlistequipment_4_02/"},
                    {"title": "4.03 Equipment Maintenance", "icon": "handyman", "link": "/admin/resources/equipmentmaintenancerecord_4_03/"},
                    {"title": "4.04 Calibration Program", "icon": "speed", "link": "/admin/resources/calibrationprogram_4_04/"},
                ]
            },
            {
                "title": "LSP-05: Metrological Traceability",
                "separator": True,
                "items": [
                    {"title": "5.01 CRM List", "icon": "science", "link": "/admin/resources/crmlist_5_01/"},
                ]
            },
            {
                "title": "LSP-06: Provided Services",
                "separator": True,
                "items": [
                    {"title": "6.01 Supplier Selection Form", "icon": "person_add", "link": "/admin/resources/supplierselection_6_01/"},
                    {"title": "6.02 Approved Supplier Service", "icon": "verified_user", "link": "/admin/resources/approvedsupplierserviceprovider_6_02/"},
                    {"title": "6.03 External Provider Eval", "icon": "fact_check", "link": "/admin/resources/externalproviderevaluation_6_03/"},
                    {"title": "6.04 Supplier Perf Monitoring", "icon": "trending_up", "link": "/admin/resources/supplierperformancemonitoring_6_04/"},
                    {"title": "6.05 Comparative Statement", "icon": "compare", "link": "/admin/resources/comparativestatement_6_05/"},
                    {"title": "6.06 Supplier Eval Plan", "icon": "event_available", "link": "/admin/resources/supplierevaluationplan_6_06/"},
                    {"title": "6.07 Store Purchase Demand", "icon": "add_shopping_cart", "link": "/admin/resources/storepurchasedemand_6_07/"},
                    {"title": "6.08 Products/Services Insp.", "icon": "inventory", "link": "/admin/resources/productsservicesinspection_6_08/"},
                ]
            },
            {
                "title": "LSP-07: Control of Documents",
                "separator": True,
                "items": [
                    {"title": "7.01 Master List of Documents", "icon": "list_alt", "link": "/admin/resources/masterlistdocument_7_01/"},
                    {"title": "7.02 Document Change Request", "icon": "edit_document", "link": "/admin/resources/documentchangerequest_7_02/"},
                ]
            },
            {
                "title": "LSP-08: Risk & Opportunities",
                "separator": True,
                "items": [
                    {"title": "8.01 Risk Management Sheet", "icon": "assignment_late", "link": "/admin/resources/riskmanagementsheet_8_01/"},
                    {"title": "8.02 Opportunity Assessment", "icon": "emoji_objects", "link": "/admin/resources/opportunityassessment_8_02/"},
                ]
            },
            {
                "title": "LSP-09: Corrective Actions",
                "separator": True,
                "items": [
                    {"title": "9.01 CAR", "icon": "assignment_turned_in", "link": "/admin/resources/correctiveactionrequest_9_01/"},
                    {"title": "9.02 CAR Log", "icon": "list", "link": "/admin/resources/correctiveactionsrequestlog_9_02/"},
                    {"title": "9.04 Root Cause Analysis", "icon": "search", "link": "/admin/resources/rootcauseanalysisform_9_04/"},
                ]
            },
            {
                "title": "LSP-10: Internal Audit",
                "separator": True,
                "items": [
                    {"title": "10.01 Audit Notification", "icon": "notifications", "link": "/admin/resources/auditnotification_10_01/"},
                    {"title": "10.02 Audit Schedule", "icon": "calendar_month", "link": "/admin/resources/auditschedule_10_02/"},
                    {"title": "10.03 MRM Schedule", "icon": "calendar_today", "link": "/admin/resources/mrmschedule_10_03/"},
                    {"title": "10.04 Trained Auditors List", "icon": "people", "link": "/admin/resources/trainedauditorslist_10_04/"},
                    {"title": "10.05 Auditor Competence", "icon": "verified", "link": "/admin/resources/auditorcompetence_10_05/"},
                    {"title": "10.06 Confidential Agreement", "icon": "gavel", "link": "/admin/resources/confidentialagreementauditors_10_06/"},
                    {"title": "10.07 Impartiality Form", "icon": "balance", "link": "/admin/resources/impartialityform_10_07/"},
                    {"title": "10.08 Internal Audit Form", "icon": "fact_check", "link": "/admin/resources/internalauditform_10_08/"},
                    {"title": "10.09 Audit Check List", "icon": "checklist", "link": "/admin/resources/internalauditchecklist_10_09/"},
                    {"title": "10.10 Audit Report", "icon": "analytics", "link": "/admin/resources/auditreport_10_10/"},
                ]
            },
            {
                "title": "LSP-11: Managerial Meetings",
                "separator": True,
                "items": [
                    {"title": "11.01 MRM Schedule", "icon": "event", "link": "/admin/resources/mrmschedule_11_01/"},
                    {"title": "11.02 MRM Notice", "icon": "campaign", "link": "/admin/resources/mrmnotice_11_02/"},
                    {"title": "11.03 MRM Agenda", "icon": "view_list", "link": "/admin/resources/mrmagenda_11_03/"},
                    {"title": "11.04 MRM Form", "icon": "assignment", "link": "/admin/resources/mrmform_11_04/"},
                ]
            },
            {
                "title": "Purchasing & Suppliers",
                "separator": True,
                "items": [
                    {"title": "Purchase Requests", "icon": "shopping_cart", "link": "/admin/resources/purchaserequest/"},
                    {"title": "Comparative Statements", "icon": "compare_arrows", "link": "/admin/resources/comparativestatement/"},
                    {"title": "Suppliers", "icon": "storefront", "link": "/admin/resources/supplier/"},
                    {"title": "Supplier Evaluation Plans", "icon": "fact_check", "link": "/admin/resources/supplierevaluationplan/"},
                    {"title": "Product/Service Inspections", "icon": "policy", "link": "/admin/resources/productserviceinspection/"},
                ]
            },
        ]
    },
    "COLORS": {
        "primary": {
            "50": "239 246 255",
            "100": "219 234 254",
            "200": "191 219 254",
            "300": "147 197 253",
            "400": "96 165 250",
            "500": "59 130 246",
            "600": "37 99 235",
            "700": "29 78 216",
            "800": "30 64 175",
            "900": "30 58 138",
        },
    },
    
    "STYLES": [
        lambda request: "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css",
    ],
    "SCRIPTS": [

        "/static/js/custom_admin.js?v=3",
    ]
}

# Render.com Production Settings
import os
import dj_database_url

if 'RENDER' in os.environ or 'DATABASE_URL' in os.environ:
    # Use PostgreSQL on Render
    db_from_env = dj_database_url.config(conn_max_age=600, ssl_require=False)
    DATABASES['default'].update(db_from_env)
    
    # Security for production
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
