import os
import dj_database_url
"""
Django settings for lims_core project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*^&^$8_!cb38b!4@ty13-e1y7cscwic(3gq+l)@9v^2dr^m&^x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'inventory',
    'reports',
    'inbox',
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework',
    'corsheaders',
    'simple_history',
    'unfold.contrib.simple_history',

    # Local apps
    'accounts',
    'samples',
    'testing',
    'resources',
    'dashboard',
    'management',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
]

AUTH_USER_MODEL = 'accounts.User'
CORS_ALLOW_ALL_ORIGINS = True # For dev only, should be restricted in prod

ROOT_URLCONF = 'lims_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lims_core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static_assets']

STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = 'dashboard_home'
LOGIN_URL = 'login'
LOGOUT_REDIRECT_URL = 'login'

UNFOLD = {
    "SITE_TITLE": "QC Lab Manager",
    "SITE_HEADER": "ISO 17025 LIMS",
    "SITE_URL": "/",

    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "1. My To-Do Inbox",
                "separator": True,
                "collapsible": False,
                "items": [
                    {"title": "Pending Approvals", "link": "/admin/inbox/inboxitem/", "icon": "inbox"},
                ]
            },
            {
                "title": "Laboratory Testing",
                "separator": True,
                "collapsible": True,
                "items": [
                    {"title": "Samples", "link": "/admin/samples/sample/", "icon": "science"},
                    {"title": "Test Results", "link": "/admin/testing/testresult/", "icon": "biotech"},
                    {"title": "Parameters", "link": "/admin/testing/parameter/", "icon": "tune"},
                    {"title": "Test Methods", "link": "/admin/testing/testmethod/", "icon": "menu_book"},
                ]
            },
            {
                "title": "Quality Management",
                "separator": True,
                "collapsible": True,
                "items": [
                    {"title": "Documents (SOPs)", "link": "/admin/management/document/", "icon": "description"},
                    {"title": "Non-Conformances", "link": "/admin/management/nonconformance/", "icon": "warning"},
                    {"title": "Corrective Actions (CAPA)", "link": "/admin/management/correctiveaction/", "icon": "build"},
                    {"title": "Internal Audits", "link": "/admin/management/internalaudit/", "icon": "fact_check"},
                    {"title": "Management Reviews", "link": "/admin/management/managementreview/", "icon": "groups"},
                    {"title": "Risks & Opportunities", "link": "/admin/management/riskopportunity/", "icon": "psychology"},
                ]
            },
            {
                "title": "Resources & Inventory",
                "separator": True,
                "collapsible": True,
                "items": [
                    {"title": "Equipment List", "link": "/admin/resources/equipment/", "icon": "precision_manufacturing"},
                    {"title": "Equipment Maintenance", "link": "/admin/resources/equipmentmaintenance/", "icon": "handyman"},
                    {"title": "Calibration Records", "link": "/admin/resources/calibrationrecord/", "icon": "speed"},
                    {"title": "Reagents & CRMs (FRM 5.01)", "link": "/admin/resources/reagentstandard/", "icon": "science"},
                    {"title": "Chemical Issuance Log", "link": "/admin/inventory/inventoryissuance/", "icon": "assignment"},
                    {"title": "Test Cost Recipes (BOM)", "link": "/admin/inventory/testbom/", "icon": "receipt_long"},
                    {"title": "Suppliers", "link": "/admin/resources/supplier/", "icon": "local_shipping"},
                    {"title": "Purchase Requests", "link": "/admin/resources/purchaserequest/", "icon": "shopping_cart"},
                    {"title": "Supplier Evaluations", "link": "/admin/resources/supplierevaluationplan/", "icon": "star"},
                    {"title": "Product Inspections", "link": "/admin/resources/productserviceinspection/", "icon": "policy"},
                    {"title": "Comparative Statements", "link": "/admin/resources/comparativestatement/", "icon": "compare_arrows"},
                ]
            },
            {
                "title": "Personnel & Competency",
                "separator": True,
                "collapsible": True,
                "items": [
                    {"title": "Personnel Authorizations", "link": "/admin/resources/personnelauthorization/", "icon": "badge"},
                    {"title": "Competency Records", "link": "/admin/resources/competencyrecord/", "icon": "school"},
                    {"title": "Competency Evaluations", "link": "/admin/resources/competencyevaluation/", "icon": "assignment_turned_in"},
                ]
            },
            {
                "title": "MIS Reports & Dashboards",
                "separator": True,
                "collapsible": True,
                "items": [
                    {"title": "Laboratory KPI Dashboard", "link": "/admin/reports/performancemetrics/", "icon": "dashboard"},
                    {"title": "On-Demand Filter Reports", "link": "/admin/reports/reportgenerator/", "icon": "filter_alt"},
                    {"title": "Costing & Financials", "link": "/admin/inventory/costingdashboard/", "icon": "attach_money"},
                ]
            },
            {
                "title": "Admin & Users",
                "separator": True,
                "collapsible": True,
                "items": [
                    {"title": "Users", "link": "/admin/auth/user/", "icon": "person"},
                    {"title": "Groups (Roles)", "link": "/admin/auth/group/", "icon": "group"},
                ]
            }
        ]
    },

    "COLORS": {
        "primary": {
            "50": "239 246 255",
            "100": "219 234 254",
            "200": "191 219 254",
            "300": "147 197 253",
            "400": "96 165 250",
            "500": "59 130 246",
            "600": "37 99 235",
            "700": "29 78 216",
            "800": "30 64 175",
            "900": "30 58 138",
        },
    },
    "SCRIPTS": [
        "/static/js/custom_admin.js?v=3",
    ]
}

# Render.com Production Settings
import os
import dj_database_url

if 'RENDER' in os.environ or 'DATABASE_URL' in os.environ:
    # Use PostgreSQL on Render
    db_from_env = dj_database_url.config(conn_max_age=600, ssl_require=False)
    DATABASES['default'].update(db_from_env)
    
    # Security for production
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
