# Generated by Django 4.2.30 on 2026-09-29 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(editable=False, help_text='Auto-generated unique ID', max_length=50, unique=True)),
                ('product_name', models.CharField(help_text='e.g., Urea, DAP, NPK 15-15-15', max_length=150)),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(help_text='Physical appearance/condition of the sample upon receipt')),
                ('storage_condition', models.CharField(default='Room Temperature', help_text='e.g., Room Temp, Refrigerated', max_length=100)),
                ('received_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('IN_PROGRESS', 'In Progress'), ('PENDING_REVIEW', 'Pending Review'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='RECEIVED', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='samples.client')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='received_samples', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
