# Generated by Django 4.2.30 on 2026-09-30 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('samples', '0002_sample_approved_at_sample_approved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSample',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('sample_id', models.CharField(db_index=True, editable=False, help_text='Auto-generated unique ID', max_length=50)),
                ('product_name', models.CharField(help_text='e.g., Urea, DAP, NPK 15-15-15', max_length=150)),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(help_text='Physical appearance/condition of the sample upon receipt')),
                ('storage_condition', models.CharField(default='Room Temperature', help_text='e.g., Room Temp, Refrigerated', max_length=100)),
                ('received_date', models.DateTimeField(blank=True, editable=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received (Pending Analysis)'), ('IN_PROGRESS', 'In Progress (Testing)'), ('PENDING_VERIFICATION', 'Pending Verification (AQCM)'), ('PENDING_APPROVAL', 'Pending Approval (QCM)'), ('APPROVED', 'Approved (CoA Ready)'), ('REJECTED', 'Rejected')], default='RECEIVED', max_length=25)),
                ('notes', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='samples.client')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical sample',
                'verbose_name_plural': 'historical samples',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
