# Generated by Django 4.2.30 on 2026-09-30 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_historicalsample'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalsample',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Sample (QCL-FRM-12.01)', 'verbose_name_plural': 'historical Samples (QCL-FRM-12.01)'},
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={'verbose_name': 'Sample (QCL-FRM-12.01)', 'verbose_name_plural': 'Samples (QCL-FRM-12.01)'},
        ),
    ]
