# Generated by Django 4.2.30 on 2026-09-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0004_alter_historicalsample_options_alter_sample_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsample',
            name='capability_decision',
            field=models.CharField(choices=[('ACCEPT', 'Accept'), ('REJECT', 'Reject')], default='ACCEPT', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalsample',
            name='environmental_conditions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalsample',
            name='exp_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsample',
            name='humidity',
            field=models.CharField(blank=True, help_text='Humidity %', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalsample',
            name='mfg_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsample',
            name='packing_condition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalsample',
            name='priority',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalsample',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsample',
            name='sample_quantity',
            field=models.CharField(blank=True, help_text='e.g., Kg/L', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalsample',
            name='sample_type_category',
            field=models.CharField(choices=[('RAW_MATERIAL', 'Raw Material'), ('BATCH_ANALYSIS', 'Batch Analysis'), ('OUTSIDE_SAMPLE', 'Outside Sample')], default='OUTSIDE_SAMPLE', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalsample',
            name='source',
            field=models.CharField(default='Vital Agri Nutrients (Pvt) Ltd', max_length=150),
        ),
        migrations.AddField(
            model_name='historicalsample',
            name='special_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsample',
            name='standard_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalsample',
            name='temperature',
            field=models.CharField(blank=True, help_text='Temperature ˚C', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalsample',
            name='uncertainty_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='capability_decision',
            field=models.CharField(choices=[('ACCEPT', 'Accept'), ('REJECT', 'Reject')], default='ACCEPT', max_length=20),
        ),
        migrations.AddField(
            model_name='sample',
            name='environmental_conditions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='exp_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='humidity',
            field=models.CharField(blank=True, help_text='Humidity %', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='mfg_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='packing_condition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='priority',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='sample',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_quantity',
            field=models.CharField(blank=True, help_text='e.g., Kg/L', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_type_category',
            field=models.CharField(choices=[('RAW_MATERIAL', 'Raw Material'), ('BATCH_ANALYSIS', 'Batch Analysis'), ('OUTSIDE_SAMPLE', 'Outside Sample')], default='OUTSIDE_SAMPLE', max_length=50),
        ),
        migrations.AddField(
            model_name='sample',
            name='source',
            field=models.CharField(default='Vital Agri Nutrients (Pvt) Ltd', max_length=150),
        ),
        migrations.AddField(
            model_name='sample',
            name='special_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='standard_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='temperature',
            field=models.CharField(blank=True, help_text='Temperature ˚C', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='uncertainty_required',
            field=models.BooleanField(default=True),
        ),
    ]
