# Generated by Django 4.2.30 on 2026-10-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0005_historicalsample_capability_decision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsample',
            name='assay',
            field=models.CharField(blank=True, help_text='Assay value for CoA', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalsample',
            name='customer_signature',
            field=models.CharField(blank=True, help_text='Customer/Sender Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalsample',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Serial # for Analysis Request', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='assay',
            field=models.CharField(blank=True, help_text='Assay value for CoA', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='customer_signature',
            field=models.CharField(blank=True, help_text='Customer/Sender Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Serial # for Analysis Request', max_length=50, null=True),
        ),
    ]
