# Generated by Django 4.2.30 on 2026-10-02 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('samples', '0006_historicalsample_assay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsample',
            name='assigned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsample',
            name='container_type',
            field=models.CharField(blank=True, help_text='e.g. Glass Bottle, Plastic Bag', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalsample',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='assigned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='container_type',
            field=models.CharField(blank=True, help_text='e.g. Glass Bottle, Plastic Bag', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SampleReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField()),
                ('reason', models.TextField(verbose_name='Reason for sample return')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='samples.sample')),
            ],
            options={
                'verbose_name': 'Sample Return (22.01)',
                'verbose_name_plural': 'Sample Returns (22.01)',
            },
        ),
        migrations.CreateModel(
            name='HistoricalSampleReturn',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('return_date', models.DateField()),
                ('reason', models.TextField(verbose_name='Reason for sample return')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='samples.sample')),
            ],
            options={
                'verbose_name': 'historical Sample Return (22.01)',
                'verbose_name_plural': 'historical Sample Returns (22.01)',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
