# Generated by Django 4.2.30 on 2026-10-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0008_historicalsamplereturn_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsample',
            name='category',
            field=models.CharField(choices=[('PSQCA', 'PSQCA'), ('SFRI', 'SFRI'), ('Raw Material', 'Raw Material'), ('Outside', 'Outside'), ('Third Party', 'Third Party')], default='Raw Material', help_text='Select sample category for serial numbering', max_length=50),
        ),
        migrations.AddField(
            model_name='sample',
            name='category',
            field=models.CharField(choices=[('PSQCA', 'PSQCA'), ('SFRI', 'SFRI'), ('Raw Material', 'Raw Material'), ('Outside', 'Outside'), ('Third Party', 'Third Party')], default='Raw Material', help_text='Select sample category for serial numbering', max_length=50),
        ),
    ]
