# Generated by Django 4.2.30 on 2026-10-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0009_historicalsample_category_sample_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsample',
            name='sample_id',
            field=models.CharField(db_index=True, editable=False, help_text='Auto-generated Analysis Request Number', max_length=50, verbose_name='AR Serial Number'),
        ),
        migrations.AlterField(
            model_name='historicalsample',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Category Serial #', max_length=50, null=True, verbose_name='Category Serial'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_id',
            field=models.CharField(editable=False, help_text='Auto-generated Analysis Request Number', max_length=50, unique=True, verbose_name='AR Serial Number'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Category Serial #', max_length=50, null=True, verbose_name='Category Serial'),
        ),
    ]
