# Generated by Django 4.2.30 on 2026-10-03 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0010_alter_historicalsample_sample_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingApproval',
            fields=[
            ],
            options={
                'verbose_name': 'Pending QCM Approval (Samples)',
                'verbose_name_plural': 'Pending QCM Approvals (Samples)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('samples.sample',),
        ),
        migrations.CreateModel(
            name='PendingVerification',
            fields=[
            ],
            options={
                'verbose_name': 'Pending AQCM Review (Samples)',
                'verbose_name_plural': 'Pending AQCM Reviews (Samples)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('samples.sample',),
        ),
    ]
