# Generated by Django 4.2.30 on 2026-09-29 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testing', '0002_alter_testresult_analyst_alter_testresult_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Analytical Balance, UV-Vis Spectrophotometer', max_length=150)),
                ('manufacturer', models.CharField(blank=True, max_length=150, null=True)),
                ('model_number', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('date_put_into_service', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active / In Use'), ('MAINTENANCE', 'Under Maintenance'), ('OUT_OF_SERVICE', 'Out of Service (Do Not Use)'), ('DECOMMISSIONED', 'Decommissioned')], default='ACTIVE', max_length=20)),
                ('location', models.CharField(blank=True, help_text='Where is the equipment located?', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CalibrationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibration_date', models.DateField()),
                ('next_due_date', models.DateField(help_text='When is the next calibration due?')),
                ('performed_by', models.CharField(help_text='Name of internal staff or external vendor', max_length=150)),
                ('certificate_number', models.CharField(blank=True, max_length=100, null=True)),
                ('passed', models.BooleanField(default=True, help_text='Did the equipment pass calibration?')),
                ('notes', models.TextField(blank=True, help_text='Details of adjustments or maintenance performed', null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibrations', to='resources.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='CompetencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_date', models.DateField(help_text='Date the training/assessment was completed')),
                ('status', models.CharField(choices=[('AUTHORIZED', 'Authorized to Perform Test'), ('IN_TRAINING', 'In Training (Supervised Only)'), ('SUSPENDED', 'Suspended / Revoked')], default='IN_TRAINING', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Reference to training evidence (e.g., passed blind sample)', null=True)),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to=settings.AUTH_USER_MODEL)),
                ('authorized_by', models.ForeignKey(help_text='The Lab Manager or QCM who authorized this analyst', on_delete=django.db.models.deletion.RESTRICT, related_name='authorizations_granted', to=settings.AUTH_USER_MODEL)),
                ('test_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.testmethod')),
            ],
            options={
                'unique_together': {('analyst', 'test_method')},
            },
        ),
    ]
