# Generated by Django 4.2.30 on 2026-09-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReagentStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., 0.1N Sulfuric Acid, Certified Reference Material (CRM)', max_length=150)),
                ('lot_number', models.CharField(max_length=100)),
                ('supplier', models.CharField(max_length=150)),
                ('receipt_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('QUARANTINED', 'Quarantined (Pending QC Verification)'), ('APPROVED', 'Approved for Use'), ('EXPIRED', 'Expired (Do Not Use)'), ('DEPLETED', 'Depleted / Discarded')], default='QUARANTINED', max_length=20)),
                ('certificate_reference', models.CharField(blank=True, help_text='CoA number provided by the manufacturer', max_length=150, null=True)),
            ],
            options={
                'unique_together': {('name', 'lot_number')},
            },
        ),
    ]
