# Generated by Django 4.2.30 on 2026-09-30 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0002_reagentstandard'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalReagentStandard',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., 0.1N Sulfuric Acid, Certified Reference Material (CRM)', max_length=150)),
                ('lot_number', models.CharField(max_length=100)),
                ('supplier', models.CharField(max_length=150)),
                ('receipt_date', models.DateField(blank=True, editable=False)),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('QUARANTINED', 'Quarantined (Pending QC Verification)'), ('APPROVED', 'Approved for Use'), ('EXPIRED', 'Expired (Do Not Use)'), ('DEPLETED', 'Depleted / Discarded')], default='QUARANTINED', max_length=20)),
                ('certificate_reference', models.CharField(blank=True, help_text='CoA number provided by the manufacturer', max_length=150, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical reagent standard',
                'verbose_name_plural': 'historical reagent standards',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEquipment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Analytical Balance, UV-Vis Spectrophotometer', max_length=150)),
                ('manufacturer', models.CharField(blank=True, max_length=150, null=True)),
                ('model_number', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(db_index=True, max_length=100)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('date_put_into_service', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active / In Use'), ('MAINTENANCE', 'Under Maintenance'), ('OUT_OF_SERVICE', 'Out of Service (Do Not Use)'), ('DECOMMISSIONED', 'Decommissioned')], default='ACTIVE', max_length=20)),
                ('location', models.CharField(blank=True, help_text='Where is the equipment located?', max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical equipment',
                'verbose_name_plural': 'historical equipments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
