# Generated by Django 4.2.30 on 2026-09-30 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_supplier_purchaserequest_historicalsupplier_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calibrationrecord',
            options={'verbose_name': 'CalibrationRecord (QCL-FRM-4.04)', 'verbose_name_plural': 'CalibrationRecords (QCL-FRM-4.04)'},
        ),
        migrations.AlterModelOptions(
            name='competencyrecord',
            options={'verbose_name': 'CompetencyRecord (QCL-FRM-1.04)', 'verbose_name_plural': 'CompetencyRecords (QCL-FRM-1.04)'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Equipment (QCL-FRM-4.02)', 'verbose_name_plural': 'Equipments (QCL-FRM-4.02)'},
        ),
        migrations.AlterModelOptions(
            name='historicalequipment',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Equipment (QCL-FRM-4.02)', 'verbose_name_plural': 'historical Equipments (QCL-FRM-4.02)'},
        ),
        migrations.AlterModelOptions(
            name='historicalpurchaserequest',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical PurchaseRequest (QCL-FRM-6.07)', 'verbose_name_plural': 'historical PurchaseRequests (QCL-FRM-6.07)'},
        ),
        migrations.AlterModelOptions(
            name='historicalsupplier',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Supplier (QCL-FRM-6.03)', 'verbose_name_plural': 'historical Suppliers (QCL-FRM-6.03)'},
        ),
        migrations.AlterModelOptions(
            name='purchaserequest',
            options={'verbose_name': 'PurchaseRequest (QCL-FRM-6.07)', 'verbose_name_plural': 'PurchaseRequests (QCL-FRM-6.07)'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Supplier (QCL-FRM-6.03)', 'verbose_name_plural': 'Suppliers (QCL-FRM-6.03)'},
        ),
    ]
