# Generated by Django 4.2.30 on 2026-09-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_alter_calibrationrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsupplier',
            name='decision',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CONTINUE', 'Continue (Existing)')], default='APPROVED', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='evaluation_type',
            field=models.CharField(choices=[('NEW', 'New Supplier'), ('EXISTING', 'Existing Supplier Re-evaluation')], default='NEW', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='sample_approved_by_qc',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('NA', 'N/A')], default='NA', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='score_fulfill_requirements',
            field=models.IntegerField(default=0, help_text='Fulfill Technical Requirement (0-3)'),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='score_lead_time',
            field=models.IntegerField(default=0, help_text='Lead Time (0-3)'),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='score_market_image',
            field=models.IntegerField(default=0, help_text='Market Image and Reputation (0-3)'),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='score_market_share',
            field=models.IntegerField(default=0, help_text='Market Share (0-3)'),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='score_order_processing',
            field=models.IntegerField(default=0, help_text='Order Processing (0-3)'),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='score_product_quality',
            field=models.IntegerField(default=0, help_text='Product Quality/Services (0-3)'),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='score_technical_capacity',
            field=models.IntegerField(default=0, help_text='Technical Capacity (0-3)'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='decision',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CONTINUE', 'Continue (Existing)')], default='APPROVED', max_length=20),
        ),
        migrations.AddField(
            model_name='supplier',
            name='evaluation_type',
            field=models.CharField(choices=[('NEW', 'New Supplier'), ('EXISTING', 'Existing Supplier Re-evaluation')], default='NEW', max_length=50),
        ),
        migrations.AddField(
            model_name='supplier',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='sample_approved_by_qc',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('NA', 'N/A')], default='NA', max_length=10),
        ),
        migrations.AddField(
            model_name='supplier',
            name='score_fulfill_requirements',
            field=models.IntegerField(default=0, help_text='Fulfill Technical Requirement (0-3)'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='score_lead_time',
            field=models.IntegerField(default=0, help_text='Lead Time (0-3)'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='score_market_image',
            field=models.IntegerField(default=0, help_text='Market Image and Reputation (0-3)'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='score_market_share',
            field=models.IntegerField(default=0, help_text='Market Share (0-3)'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='score_order_processing',
            field=models.IntegerField(default=0, help_text='Order Processing (0-3)'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='score_product_quality',
            field=models.IntegerField(default=0, help_text='Product Quality/Services (0-3)'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='score_technical_capacity',
            field=models.IntegerField(default=0, help_text='Technical Capacity (0-3)'),
        ),
    ]
