# Generated by Django 4.2.30 on 2026-09-30 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0007_historicaltestresult_specs_testresult_specs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0006_historicalsupplier_decision_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competencyrecord',
            options={'verbose_name': 'Competency Monitoring (QCL-FRM-1.04)', 'verbose_name_plural': 'Competency Monitoring (QCL-FRM-1.04)'},
        ),
        migrations.AlterUniqueTogether(
            name='competencyrecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='competencyrecord',
            name='assessor',
            field=models.CharField(blank=True, help_text='Who conducted the assessment? (e.g., QCM or External Expert)', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='competencyrecord',
            name='comments',
            field=models.TextField(blank=True, help_text='Assessment notes or areas for improvement', null=True),
        ),
        migrations.AddField(
            model_name='competencyrecord',
            name='score_challenge_testing',
            field=models.IntegerField(choices=[(4, '4 - High Competence (Completes task independently)'), (3, '3 - Partial Competence (Need occasional support)'), (2, '2 - Low Competence (Needs ongoing support)'), (1, '1 - No Competence (Needs Training & direction)')], default=1),
        ),
        migrations.AddField(
            model_name='competencyrecord',
            name='score_education',
            field=models.IntegerField(choices=[(4, '4 - High Competence (Completes task independently)'), (3, '3 - Partial Competence (Need occasional support)'), (2, '2 - Low Competence (Needs ongoing support)'), (1, '1 - No Competence (Needs Training & direction)')], default=1),
        ),
        migrations.AddField(
            model_name='competencyrecord',
            name='score_experience',
            field=models.IntegerField(choices=[(4, '4 - High Competence (Completes task independently)'), (3, '3 - Partial Competence (Need occasional support)'), (2, '2 - Low Competence (Needs ongoing support)'), (1, '1 - No Competence (Needs Training & direction)')], default=1),
        ),
        migrations.AddField(
            model_name='competencyrecord',
            name='score_proficiency_testing',
            field=models.IntegerField(choices=[(4, '4 - High Competence (Completes task independently)'), (3, '3 - Partial Competence (Need occasional support)'), (2, '2 - Low Competence (Needs ongoing support)'), (1, '1 - No Competence (Needs Training & direction)')], default=1),
        ),
        migrations.AddField(
            model_name='competencyrecord',
            name='score_qualification',
            field=models.IntegerField(choices=[(4, '4 - High Competence (Completes task independently)'), (3, '3 - Partial Competence (Need occasional support)'), (2, '2 - Low Competence (Needs ongoing support)'), (1, '1 - No Competence (Needs Training & direction)')], default=1),
        ),
        migrations.AddField(
            model_name='competencyrecord',
            name='score_skills',
            field=models.IntegerField(choices=[(4, '4 - High Competence (Completes task independently)'), (3, '3 - Partial Competence (Need occasional support)'), (2, '2 - Low Competence (Needs ongoing support)'), (1, '1 - No Competence (Needs Training & direction)')], default=1),
        ),
        migrations.AddField(
            model_name='competencyrecord',
            name='score_technical_knowledge',
            field=models.IntegerField(choices=[(4, '4 - High Competence (Completes task independently)'), (3, '3 - Partial Competence (Need occasional support)'), (2, '2 - Low Competence (Needs ongoing support)'), (1, '1 - No Competence (Needs Training & direction)')], default=1),
        ),
        migrations.AddField(
            model_name='competencyrecord',
            name='score_training',
            field=models.IntegerField(choices=[(4, '4 - High Competence (Completes task independently)'), (3, '3 - Partial Competence (Need occasional support)'), (2, '2 - Low Competence (Needs ongoing support)'), (1, '1 - No Competence (Needs Training & direction)')], default=1),
        ),
        migrations.AlterField(
            model_name='competencyrecord',
            name='authorized_by',
            field=models.ForeignKey(blank=True, help_text='The Lab Manager or QCM who authorized this analyst', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='authorizations_granted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='competencyrecord',
            name='test_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testing.testmethod'),
        ),
    ]
