# Generated by Django 4.2.30 on 2026-10-01 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0007_alter_competencyrecord_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetencyEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateField(help_text='Date of Supervision')),
                ('score_analysis_skills', models.CharField(choices=[('E', 'Exceptional (Hold Full Command, Can Supervise)'), ('HC', 'Highly Competent (Can Supervise Lab Activities)'), ('C', 'Competent (Can Work Independently)'), ('AC', 'Approaching Competence (Can Work Under Supervision)'), ('ND', 'Needs Development (Lacks Basics, Needs Training)')], default='ND', max_length=2, verbose_name='Analysis Skills')),
                ('score_equipment_handling', models.CharField(choices=[('E', 'Exceptional (Hold Full Command, Can Supervise)'), ('HC', 'Highly Competent (Can Supervise Lab Activities)'), ('C', 'Competent (Can Work Independently)'), ('AC', 'Approaching Competence (Can Work Under Supervision)'), ('ND', 'Needs Development (Lacks Basics, Needs Training)')], default='ND', max_length=2, verbose_name='Lab Equipment Handling')),
                ('score_iso_awareness', models.CharField(choices=[('E', 'Exceptional (Hold Full Command, Can Supervise)'), ('HC', 'Highly Competent (Can Supervise Lab Activities)'), ('C', 'Competent (Can Work Independently)'), ('AC', 'Approaching Competence (Can Work Under Supervision)'), ('ND', 'Needs Development (Lacks Basics, Needs Training)')], default='ND', max_length=2, verbose_name='Awareness ISO 17025: 2023')),
                ('score_testing_skills', models.CharField(choices=[('E', 'Exceptional (Hold Full Command, Can Supervise)'), ('HC', 'Highly Competent (Can Supervise Lab Activities)'), ('C', 'Competent (Can Work Independently)'), ('AC', 'Approaching Competence (Can Work Under Supervision)'), ('ND', 'Needs Development (Lacks Basics, Needs Training)')], default='ND', max_length=2, verbose_name='Testing Skills')),
                ('score_sample_prep', models.CharField(choices=[('E', 'Exceptional (Hold Full Command, Can Supervise)'), ('HC', 'Highly Competent (Can Supervise Lab Activities)'), ('C', 'Competent (Can Work Independently)'), ('AC', 'Approaching Competence (Can Work Under Supervision)'), ('ND', 'Needs Development (Lacks Basics, Needs Training)')], default='ND', max_length=2, verbose_name='Sample Preparation Skills')),
                ('remarks', models.TextField(blank=True, help_text='Remarks / Comments', null=True)),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(help_text='Supervisor / Evaluator', on_delete=django.db.models.deletion.RESTRICT, related_name='evaluations_conducted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Competency Evaluation (QCL-FRM-2.09)',
                'verbose_name_plural': 'Competency Evaluations (QCL-FRM-2.09)',
            },
        ),
    ]
