# Generated by Django 4.2.30 on 2026-10-01 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_competencyevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='calibration_frequency',
            field=models.CharField(blank=True, help_text='e.g., Annually, 6 Months', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='identification_no',
            field=models.CharField(blank=True, help_text='Internal ID e.g., EQ-01', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='maintenance_frequency',
            field=models.CharField(blank=True, help_text='e.g., Weekly, Monthly', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='operating_range',
            field=models.CharField(blank=True, help_text='e.g., 0-200g, 190-1100nm', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalequipment',
            name='calibration_frequency',
            field=models.CharField(blank=True, help_text='e.g., Annually, 6 Months', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalequipment',
            name='identification_no',
            field=models.CharField(blank=True, help_text='Internal ID e.g., EQ-01', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalequipment',
            name='maintenance_frequency',
            field=models.CharField(blank=True, help_text='e.g., Weekly, Monthly', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalequipment',
            name='operating_range',
            field=models.CharField(blank=True, help_text='e.g., 0-200g, 190-1100nm', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='EquipmentMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField()),
                ('parts_repaired_replaced', models.CharField(blank=True, help_text='If any', max_length=255, null=True)),
                ('maintenance_by', models.CharField(help_text='Who performed the maintenance?', max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='resources.equipment')),
            ],
            options={
                'verbose_name': 'Maintenance Record (QCL-FRM-4.03)',
                'verbose_name_plural': 'Maintenance Records (QCL-FRM-4.03)',
            },
        ),
    ]
