# Generated by Django 4.2.30 on 2026-10-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_equipment_calibration_frequency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalpurchaserequest',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Purchase Request (QCL-FRM-6.07)', 'verbose_name_plural': 'historical Purchase Requests (QCL-FRM-6.07)'},
        ),
        migrations.AlterModelOptions(
            name='purchaserequest',
            options={'verbose_name': 'Purchase Request (QCL-FRM-6.07)', 'verbose_name_plural': 'Purchase Requests (QCL-FRM-6.07)'},
        ),
        migrations.RemoveField(
            model_name='historicalpurchaserequest',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='quantity',
        ),
        migrations.AddField(
            model_name='historicalpurchaserequest',
            name='purpose',
            field=models.CharField(blank=True, help_text='Purpose of Purchase', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalpurchaserequest',
            name='quantity_required',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='historicalpurchaserequest',
            name='specification',
            field=models.CharField(blank=True, help_text='Model, Brand, Quality, Capacity', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalpurchaserequest',
            name='stock_in_hand',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='purpose',
            field=models.CharField(blank=True, help_text='Purpose of Purchase', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='quantity_required',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='specification',
            field=models.CharField(blank=True, help_text='Model, Brand, Quality, Capacity', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='stock_in_hand',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalpurchaserequest',
            name='item_description',
            field=models.CharField(max_length=255, verbose_name='Item Name'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='item_description',
            field=models.CharField(max_length=255, verbose_name='Item Name'),
        ),
    ]
