# Generated by Django 4.2.30 on 2026-10-01 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0011_historicalsupplier_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencyevaluation',
            name='manager_qc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmentmaintenance',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_maintenances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmentmaintenance',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_maintenances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmentmaintenance',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_maintenances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpurchaserequest',
            name='insp_mints_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Insp Mints NO & Date'),
        ),
        migrations.AddField(
            model_name='historicalpurchaserequest',
            name='service_call_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Service Call No & Date'),
        ),
        migrations.AddField(
            model_name='historicalpurchaserequest',
            name='spd_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SPD No'),
        ),
        migrations.AddField(
            model_name='historicalpurchaserequest',
            name='store_keeper',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='insp_mints_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Insp Mints NO & Date'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='service_call_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Service Call No & Date'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='spd_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SPD No'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='store_keeper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_keeper_purchases', to=settings.AUTH_USER_MODEL),
        ),
    ]
