# Generated by Django 4.2.30 on 2026-10-01 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0014_competencyrecord_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsupplier',
            name='crit_10_crm_coa',
            field=models.BooleanField(default=False, verbose_name='Provides CoA & uncertainty (ISO/IEC 17034 certified)'),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='crit_10_evidence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='crit_1_evidence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='crit_1_registered',
            field=models.BooleanField(default=False, verbose_name='Supplier is legally registered'),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='crit_2_evidence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='crit_2_market_1yr',
            field=models.BooleanField(default=False, verbose_name='At least 1 year in market'),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='crit_3_evidence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='crit_3_offers_range',
            field=models.BooleanField(default=False, verbose_name='Offers required range of products/services'),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='crit_4_equipment_docs',
            field=models.BooleanField(default=False, verbose_name='Fulfills tech specs & provides docs (manuals/training)'),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='crit_4_evidence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='crit_5_calibration_traceability',
            field=models.BooleanField(default=False, verbose_name='Capability for traceability, uncertainty, range'),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='crit_5_evidence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='crit_6_evidence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='crit_6_iso17025',
            field=models.BooleanField(default=False, verbose_name='Accredited on ISO/IEC 17025'),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='crit_7_evidence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='crit_7_iso17043',
            field=models.BooleanField(default=False, verbose_name='Accredited for PT services (ISO/IEC 17043)'),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='crit_8_evidence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='crit_8_training_exp',
            field=models.BooleanField(default=False, verbose_name='Experience & Qualification of Trainers (PNAC preferred)'),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='crit_9_evidence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='crit_9_msds',
            field=models.BooleanField(default=False, verbose_name='Provides supporting docs / MSDS'),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='requirements_from_supplier',
            field=models.TextField(blank=True, help_text='Range of products/services required', null=True),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='selection_evaluator',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Selection Evaluator'),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='crit_10_crm_coa',
            field=models.BooleanField(default=False, verbose_name='Provides CoA & uncertainty (ISO/IEC 17034 certified)'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='crit_10_evidence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='crit_1_evidence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='crit_1_registered',
            field=models.BooleanField(default=False, verbose_name='Supplier is legally registered'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='crit_2_evidence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='crit_2_market_1yr',
            field=models.BooleanField(default=False, verbose_name='At least 1 year in market'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='crit_3_evidence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='crit_3_offers_range',
            field=models.BooleanField(default=False, verbose_name='Offers required range of products/services'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='crit_4_equipment_docs',
            field=models.BooleanField(default=False, verbose_name='Fulfills tech specs & provides docs (manuals/training)'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='crit_4_evidence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='crit_5_calibration_traceability',
            field=models.BooleanField(default=False, verbose_name='Capability for traceability, uncertainty, range'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='crit_5_evidence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='crit_6_evidence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='crit_6_iso17025',
            field=models.BooleanField(default=False, verbose_name='Accredited on ISO/IEC 17025'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='crit_7_evidence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='crit_7_iso17043',
            field=models.BooleanField(default=False, verbose_name='Accredited for PT services (ISO/IEC 17043)'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='crit_8_evidence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='crit_8_training_exp',
            field=models.BooleanField(default=False, verbose_name='Experience & Qualification of Trainers (PNAC preferred)'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='crit_9_evidence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='crit_9_msds',
            field=models.BooleanField(default=False, verbose_name='Provides supporting docs / MSDS'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='requirements_from_supplier',
            field=models.TextField(blank=True, help_text='Range of products/services required', null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='selection_evaluator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_selections_evaluated', to=settings.AUTH_USER_MODEL, verbose_name='Selection Evaluator'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
