# Generated by Django 4.2.30 on 2026-10-02 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0015_historicalsupplier_crit_10_crm_coa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductServiceInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_type', models.CharField(choices=[('PRODUCT', 'Products'), ('SERVICE', 'Services')], max_length=20)),
                ('description', models.CharField(max_length=200, verbose_name='Products/Services')),
                ('provider_status', models.CharField(choices=[('NEW', 'Newly engaged'), ('EXISTING', 'Pre-existing')], max_length=20)),
                ('gate_pass_no', models.CharField(blank=True, max_length=50, null=True)),
                ('pr_po_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='PR No./PO No.')),
                ('invoice_no', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_receipt', models.DateField()),
                ('prod_coa_remarks', models.CharField(blank=True, max_length=200, null=True, verbose_name='Product COA Remarks')),
                ('prod_spec_remarks', models.CharField(blank=True, max_length=200, null=True, verbose_name='Specification Remarks')),
                ('prod_qty_remarks', models.CharField(blank=True, max_length=200, null=True, verbose_name='Quantity Remarks')),
                ('prod_lot_remarks', models.CharField(blank=True, max_length=200, null=True, verbose_name='Verification of Lot No. Remarks')),
                ('prod_mfg_remarks', models.CharField(blank=True, max_length=200, null=True, verbose_name='MFG Date Remarks')),
                ('prod_exp_remarks', models.CharField(blank=True, max_length=200, null=True, verbose_name='EXP Date Remarks')),
                ('prod_model_remarks', models.CharField(blank=True, max_length=200, null=True, verbose_name='Model/Make Remarks')),
                ('srv_traceability_remarks', models.CharField(blank=True, max_length=200, null=True, verbose_name='Traceability of accreditation Remarks')),
                ('srv_scope_remarks', models.CharField(blank=True, max_length=200, null=True, verbose_name='Scope of Accreditation Remarks')),
                ('srv_training_remarks', models.CharField(blank=True, max_length=200, null=True, verbose_name='Traceability of Training Remarks')),
                ('srv_response_remarks', models.CharField(blank=True, max_length=200, null=True, verbose_name='Response to queries Remarks')),
                ('srv_skills_remarks', models.CharField(blank=True, max_length=200, null=True, verbose_name='Trainer/engineer skills Remarks')),
                ('srv_validity_remarks', models.CharField(blank=True, max_length=200, null=True, verbose_name='Validity of certificate Remarks')),
                ('status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], max_length=20)),
                ('external_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='resources.supplier')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='received_inspections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inspection (QCL-FRM-6.08)',
                'verbose_name_plural': 'Inspections (QCL-FRM-6.08)',
            },
        ),
    ]
