# Generated by Django 4.2.30 on 2026-10-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0016_productserviceinspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreagentstandard',
            name='catalog_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cat No.'),
        ),
        migrations.AddField(
            model_name='historicalreagentstandard',
            name='is_crm',
            field=models.BooleanField(default=False, verbose_name='Is Certified Reference Material (CRM)'),
        ),
        migrations.AddField(
            model_name='historicalreagentstandard',
            name='quantity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='historicalreagentstandard',
            name='traceability',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Traceability (e.g., NIST)'),
        ),
        migrations.AddField(
            model_name='reagentstandard',
            name='catalog_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cat No.'),
        ),
        migrations.AddField(
            model_name='reagentstandard',
            name='is_crm',
            field=models.BooleanField(default=False, verbose_name='Is Certified Reference Material (CRM)'),
        ),
        migrations.AddField(
            model_name='reagentstandard',
            name='quantity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='reagentstandard',
            name='traceability',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Traceability (e.g., NIST)'),
        ),
    ]
