# Generated by Django 4.2.30 on 2026-10-03 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0024_add_na_equipment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comparativestatement',
            options={'verbose_name': 'Comparative Statement (QCL-FRM-6.05)', 'verbose_name_plural': 'Comparative Statement (QCL-FRM-6.05)s'},
        ),
        migrations.AlterModelOptions(
            name='historicalcomparativestatement',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Comparative Statement (QCL-FRM-6.05)', 'verbose_name_plural': 'historical Comparative Statement (QCL-FRM-6.05)s'},
        ),
        migrations.AlterModelOptions(
            name='historicalreagentstandard',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical CRM / Reagent List (QCL-FRM-5.01)', 'verbose_name_plural': 'historical CRM / Reagent Lists (QCL-FRM-5.01)'},
        ),
        migrations.AlterModelOptions(
            name='historicalsupplierevaluationplan',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Supplier Evaluation Plan (QCL-FRM-6.06)', 'verbose_name_plural': 'historical Supplier Evaluation Plan (QCL-FRM-6.06)s'},
        ),
        migrations.AlterModelOptions(
            name='reagentstandard',
            options={'verbose_name': 'CRM / Reagent List (QCL-FRM-5.01)', 'verbose_name_plural': 'CRM / Reagent Lists (QCL-FRM-5.01)'},
        ),
        migrations.AlterModelOptions(
            name='supplierevaluationplan',
            options={'verbose_name': 'Supplier Evaluation Plan (QCL-FRM-6.06)', 'verbose_name_plural': 'Supplier Evaluation Plan (QCL-FRM-6.06)s'},
        ),
    ]
