# Generated by Django 4.2.30 on 2026-10-07 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0025_alter_comparativestatement_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalPersonnelList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.CharField(max_length=20)),
                ('date_issued', models.DateField()),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='iso_personnel/')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'List of Technical Personnel (1.03)',
                'verbose_name_plural': 'List of Technical Personnel (1.03)',
            },
        ),
        migrations.CreateModel(
            name='PersonnelAuthorizationPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_permits', to=settings.AUTH_USER_MODEL)),
                ('authorized_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_permits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personnel Authorization Permit (1.01)',
                'verbose_name_plural': 'Personnel Authorization Permits (1.01)',
            },
        ),
        migrations.CreateModel(
            name='GradingMatrixProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product_category', models.CharField(max_length=100)),
                ('sample_prep_skill', models.CharField(choices=[('E', 'Exceptional'), ('HC', 'Highly Competent'), ('C', 'Competent'), ('AC', 'Approaching Competence'), ('ND', 'Needs Development')], default='ND', max_length=2)),
                ('testing_skill', models.CharField(choices=[('E', 'Exceptional'), ('HC', 'Highly Competent'), ('C', 'Competent'), ('AC', 'Approaching Competence'), ('ND', 'Needs Development')], default='ND', max_length=2)),
                ('overall_grade', models.CharField(choices=[('E', 'Exceptional'), ('HC', 'Highly Competent'), ('C', 'Competent'), ('AC', 'Approaching Competence'), ('ND', 'Needs Development')], default='ND', max_length=2)),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('evaluator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grading Matrix Product (1.01F)',
                'verbose_name_plural': 'Grading Matrix Product (1.01F)',
            },
        ),
        migrations.CreateModel(
            name='GradingMatrixEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('equipment_name', models.CharField(max_length=100)),
                ('calibration_check', models.CharField(choices=[('E', 'Exceptional'), ('HC', 'Highly Competent'), ('C', 'Competent'), ('AC', 'Approaching Competence'), ('ND', 'Needs Development')], default='ND', max_length=2)),
                ('operation_skill', models.CharField(choices=[('E', 'Exceptional'), ('HC', 'Highly Competent'), ('C', 'Competent'), ('AC', 'Approaching Competence'), ('ND', 'Needs Development')], default='ND', max_length=2)),
                ('maintenance_skill', models.CharField(choices=[('E', 'Exceptional'), ('HC', 'Highly Competent'), ('C', 'Competent'), ('AC', 'Approaching Competence'), ('ND', 'Needs Development')], default='ND', max_length=2)),
                ('overall_grade', models.CharField(choices=[('E', 'Exceptional'), ('HC', 'Highly Competent'), ('C', 'Competent'), ('AC', 'Approaching Competence'), ('ND', 'Needs Development')], default='ND', max_length=2)),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('evaluator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grading Matrix Equipment (1.01E)',
                'verbose_name_plural': 'Grading Matrix Equipment (1.01E)',
            },
        ),
        migrations.CreateModel(
            name='GradingMatrixDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('document_comprehension', models.CharField(choices=[('E', 'Exceptional'), ('HC', 'Highly Competent'), ('C', 'Competent'), ('AC', 'Approaching Competence'), ('ND', 'Needs Development')], default='ND', max_length=2)),
                ('record_keeping', models.CharField(choices=[('E', 'Exceptional'), ('HC', 'Highly Competent'), ('C', 'Competent'), ('AC', 'Approaching Competence'), ('ND', 'Needs Development')], default='ND', max_length=2)),
                ('iso_awareness', models.CharField(choices=[('E', 'Exceptional'), ('HC', 'Highly Competent'), ('C', 'Competent'), ('AC', 'Approaching Competence'), ('ND', 'Needs Development')], default='ND', max_length=2)),
                ('overall_grade', models.CharField(choices=[('E', 'Exceptional'), ('HC', 'Highly Competent'), ('C', 'Competent'), ('AC', 'Approaching Competence'), ('ND', 'Needs Development')], default='ND', max_length=2)),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('evaluator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grading Matrix Document (1.01G)',
                'verbose_name_plural': 'Grading Matrix Document (1.01G)',
            },
        ),
        migrations.CreateModel(
            name='CompetencyEvalPTSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateField()),
                ('pt_round_name', models.CharField(max_length=100)),
                ('parameter_tested', models.CharField(max_length=100)),
                ('z_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('result_status', models.CharField(choices=[('SATISFACTORY', 'Satisfactory'), ('UNSATISFACTORY', 'Unsatisfactory')], max_length=20)),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('evaluator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Eval PT Samples (1.01D)',
                'verbose_name_plural': 'Eval PT Samples (1.01D)',
            },
        ),
        migrations.CreateModel(
            name='CompetencyEvalInternalSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateField()),
                ('sample_id', models.CharField(max_length=100)),
                ('parameter_tested', models.CharField(max_length=100)),
                ('result_status', models.CharField(choices=[('SATISFACTORY', 'Satisfactory'), ('UNSATISFACTORY', 'Unsatisfactory')], max_length=20)),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('evaluator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Eval Internal Samples (1.01C)',
                'verbose_name_plural': 'Eval Internal Samples (1.01C)',
            },
        ),
        migrations.CreateModel(
            name='AuthorizedAnalystList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.CharField(max_length=20)),
                ('date_issued', models.DateField()),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='iso_personnel/')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'List of Authorized Analysts (1.02)',
                'verbose_name_plural': 'List of Authorized Analysts (1.02)',
            },
        ),
        migrations.CreateModel(
            name='AnalystAuthorizationTestInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_or_instrument_name', models.CharField(max_length=255)),
                ('authorization_status', models.CharField(choices=[('AUTHORIZED', 'Authorized'), ('UNDER_SUPERVISION', 'Under Supervision')], max_length=50)),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_authorizations', to='resources.personnelauthorizationpermit')),
            ],
            options={
                'verbose_name': 'Analyst Auth Tests/Instruments (1.01A)',
                'verbose_name_plural': 'Analyst Auth Tests/Instruments (1.01A)',
            },
        ),
        migrations.CreateModel(
            name='AnalystAuthorizationProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('authorization_status', models.CharField(choices=[('AUTHORIZED', 'Authorized'), ('UNDER_SUPERVISION', 'Under Supervision')], max_length=50)),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_authorizations', to='resources.personnelauthorizationpermit')),
            ],
            options={
                'verbose_name': 'Product & Sample Auth (1.01B)',
                'verbose_name_plural': 'Product & Sample Auth (1.01B)',
            },
        ),
    ]
