# Generated by Django 4.2.30 on 2026-10-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0025_alter_comparativestatement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreagentstandard',
            name='current_stock',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Current Stock'),
        ),
        migrations.AddField(
            model_name='historicalreagentstandard',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Cost per single unit of measure', max_digits=10),
        ),
        migrations.AddField(
            model_name='historicalreagentstandard',
            name='unit_of_measure',
            field=models.CharField(default='g', help_text='e.g., g, ml, L, unit', max_length=20),
        ),
        migrations.AddField(
            model_name='reagentstandard',
            name='current_stock',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Current Stock'),
        ),
        migrations.AddField(
            model_name='reagentstandard',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Cost per single unit of measure', max_digits=10),
        ),
        migrations.AddField(
            model_name='reagentstandard',
            name='unit_of_measure',
            field=models.CharField(default='g', help_text='e.g., g, ml, L, unit', max_length=20),
        ),
    ]
