# Generated by Django 4.2.30 on 2026-10-07 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0025_alter_comparativestatement_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Instrument Room, Microbiology Lab, Wet Lab', max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('target_temperature_min', models.DecimalField(blank=True, decimal_places=2, help_text='Min Temp (°C)', max_digits=5, null=True)),
                ('target_temperature_max', models.DecimalField(blank=True, decimal_places=2, help_text='Max Temp (°C)', max_digits=5, null=True)),
                ('target_humidity_min', models.DecimalField(blank=True, decimal_places=2, help_text='Min Humidity (% RH)', max_digits=5, null=True)),
                ('target_humidity_max', models.DecimalField(blank=True, decimal_places=2, help_text='Max Humidity (% RH)', max_digits=5, null=True)),
            ],
            options={
                'verbose_name': 'Facility Area (6.3)',
                'verbose_name_plural': 'Facility Areas (6.3)',
            },
        ),
        migrations.CreateModel(
            name='HistoricalFacilityArea',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Instrument Room, Microbiology Lab, Wet Lab', max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('target_temperature_min', models.DecimalField(blank=True, decimal_places=2, help_text='Min Temp (°C)', max_digits=5, null=True)),
                ('target_temperature_max', models.DecimalField(blank=True, decimal_places=2, help_text='Max Temp (°C)', max_digits=5, null=True)),
                ('target_humidity_min', models.DecimalField(blank=True, decimal_places=2, help_text='Min Humidity (% RH)', max_digits=5, null=True)),
                ('target_humidity_max', models.DecimalField(blank=True, decimal_places=2, help_text='Max Humidity (% RH)', max_digits=5, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Facility Area (6.3)',
                'verbose_name_plural': 'historical Facility Areas (6.3)',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEnvironmentalLog',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temperature (°C)')),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Humidity (% RH)')),
                ('remarks', models.TextField(blank=True, help_text='Note any deviations, excursions, or corrective actions taken.', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('area', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='resources.facilityarea')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('measuring_instrument', models.ForeignKey(blank=True, db_constraint=False, help_text='Equipment used to measure conditions', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='resources.equipment')),
                ('recorded_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Environmental Log (6.3)',
                'verbose_name_plural': 'historical Environmental Logs (6.3)',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='EnvironmentalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temperature (°C)')),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Humidity (% RH)')),
                ('remarks', models.TextField(blank=True, help_text='Note any deviations, excursions, or corrective actions taken.', null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environmental_logs', to='resources.facilityarea')),
                ('measuring_instrument', models.ForeignKey(blank=True, help_text='Equipment used to measure conditions', null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.equipment')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_environmental_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Environmental Log (6.3)',
                'verbose_name_plural': 'Environmental Logs (6.3)',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
