# Generated by Django 4.2.30 on 2026-10-07 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0026_technicalpersonnellist_personnelauthorizationpermit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualTrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.CharField(max_length=50)),
                ('plan_no', models.CharField(max_length=50)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Annual Training Plan (2.03)',
                'verbose_name_plural': 'Annual Training Plans (2.03)',
            },
        ),
        migrations.CreateModel(
            name='TrainingAttendanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('date_held', models.DateField()),
                ('time_held', models.TimeField()),
                ('venue', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=255)),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance Sheet (2.04)',
                'verbose_name_plural': 'Attendance Sheets (2.04)',
            },
        ),
        migrations.CreateModel(
            name='TrainingPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('section', models.CharField(max_length=100)),
                ('training_type', models.CharField(choices=[('INTERNAL', 'Internal'), ('EXTERNAL', 'External')], max_length=50)),
                ('duration', models.CharField(max_length=100)),
                ('resource', models.CharField(max_length=100)),
                ('num_personnel', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='resources.annualtrainingplan')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingNeedAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_year', models.IntegerField()),
                ('amendment_no', models.CharField(blank=True, max_length=20)),
                ('score_work_output', models.IntegerField(help_text='Neatness, accuracy, on-time completion (out of 100)')),
                ('score_initiative', models.IntegerField(help_text='Corrective/preventive actions, suggestions')),
                ('score_validation', models.IntegerField(help_text='Validation of Analytical Methods and STM')),
                ('score_equipment', models.IntegerField(help_text='Equipment Operation')),
                ('score_audit', models.IntegerField(help_text='Internal Audit ISO 17025')),
                ('score_sample_handling', models.IntegerField(help_text='Sample Handling')),
                ('score_reporting', models.IntegerField(help_text='Reporting, Opinion and Interpretation')),
                ('trainings_required', models.TextField(help_text='List of trainings required, separated by newlines')),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Training Need Assessment (2.02)',
                'verbose_name_plural': 'Training Need Assessments (2.02)',
            },
        ),
        migrations.CreateModel(
            name='TrainingFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('instructor_rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comments', models.TextField(blank=True)),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.trainingattendancesheet')),
            ],
            options={
                'verbose_name': 'Training Feedback (2.07)',
                'verbose_name_plural': 'Training Feedbacks (2.07)',
            },
        ),
        migrations.CreateModel(
            name='TrainingEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateField()),
                ('score', models.IntegerField(help_text='Score or grade')),
                ('remarks', models.TextField(blank=True)),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('evaluator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.trainingattendancesheet')),
            ],
            options={
                'verbose_name': 'Training Evaluation (2.05)',
                'verbose_name_plural': 'Training Evaluations (2.05)',
            },
        ),
        migrations.CreateModel(
            name='TrainerEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('knowledge_rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('communication_rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('overall_rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('evaluator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluated_as_trainer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trainer Evaluation (2.12)',
                'verbose_name_plural': 'Trainer Evaluations (2.12)',
            },
        ),
        migrations.CreateModel(
            name='OrientationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('department', models.CharField(max_length=100)),
                ('topics_covered', models.TextField()),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orientation Plan (2.09)',
                'verbose_name_plural': 'Orientation Plans (2.09)',
            },
        ),
        migrations.CreateModel(
            name='IndividualTrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_title', models.CharField(max_length=255)),
                ('date_completed', models.DateField()),
                ('result', models.CharField(max_length=100)),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Individual Training Record (2.08)',
                'verbose_name_plural': 'Individual Training Records (2.08)',
            },
        ),
        migrations.CreateModel(
            name='CompetenceReassessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason_for_reassessment', models.TextField()),
                ('outcome', models.CharField(max_length=255)),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('evaluator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Competence Reassessment (2.10)',
                'verbose_name_plural': 'Competence Reassessments (2.10)',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='resources.trainingattendancesheet')),
            ],
        ),
    ]
