# Generated by Django 4.2.30 on 2026-10-07 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0028_remove_individualtrainingrecord_result_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competencyevalinternalsample',
            name='evaluator',
        ),
        migrations.RemoveField(
            model_name='competencyevalinternalsample',
            name='parameter_tested',
        ),
        migrations.RemoveField(
            model_name='competencyevalinternalsample',
            name='result_status',
        ),
        migrations.RemoveField(
            model_name='competencyevalinternalsample',
            name='sample_id',
        ),
        migrations.RemoveField(
            model_name='competencyevalptsample',
            name='evaluator',
        ),
        migrations.RemoveField(
            model_name='competencyevalptsample',
            name='parameter_tested',
        ),
        migrations.RemoveField(
            model_name='competencyevalptsample',
            name='result_status',
        ),
        migrations.RemoveField(
            model_name='competencyevalptsample',
            name='z_score',
        ),
        migrations.RemoveField(
            model_name='gradingmatrixdocument',
            name='document_comprehension',
        ),
        migrations.RemoveField(
            model_name='gradingmatrixdocument',
            name='evaluator',
        ),
        migrations.RemoveField(
            model_name='gradingmatrixdocument',
            name='iso_awareness',
        ),
        migrations.RemoveField(
            model_name='gradingmatrixdocument',
            name='overall_grade',
        ),
        migrations.RemoveField(
            model_name='gradingmatrixdocument',
            name='record_keeping',
        ),
        migrations.RemoveField(
            model_name='gradingmatrixequipment',
            name='calibration_check',
        ),
        migrations.RemoveField(
            model_name='gradingmatrixequipment',
            name='equipment_name',
        ),
        migrations.RemoveField(
            model_name='gradingmatrixequipment',
            name='evaluator',
        ),
        migrations.RemoveField(
            model_name='gradingmatrixequipment',
            name='maintenance_skill',
        ),
        migrations.RemoveField(
            model_name='gradingmatrixequipment',
            name='operation_skill',
        ),
        migrations.RemoveField(
            model_name='gradingmatrixequipment',
            name='overall_grade',
        ),
        migrations.RemoveField(
            model_name='gradingmatrixproduct',
            name='evaluator',
        ),
        migrations.RemoveField(
            model_name='gradingmatrixproduct',
            name='overall_grade',
        ),
        migrations.RemoveField(
            model_name='gradingmatrixproduct',
            name='product_category',
        ),
        migrations.RemoveField(
            model_name='gradingmatrixproduct',
            name='sample_prep_skill',
        ),
        migrations.RemoveField(
            model_name='gradingmatrixproduct',
            name='testing_skill',
        ),
        migrations.AddField(
            model_name='annualtrainingplan',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annualtrainingplan',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annualtrainingplan',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annualtrainingplan',
            name='prepared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annualtrainingplan',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PREPARED', 'Prepared / Submitted'), ('CHECKED', 'Checked / Reviewed'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='authorizedanalystlist',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authorizedanalystlist',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authorizedanalystlist',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='authorizedanalystlist',
            name='prepared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authorizedanalystlist',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='authorizedanalystlist',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PREPARED', 'Prepared / Submitted'), ('CHECKED', 'Checked / Reviewed'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='competencereassessment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competencereassessment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competencereassessment',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competencereassessment',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competencereassessment',
            name='prepared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competencereassessment',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competencereassessment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PREPARED', 'Prepared / Submitted'), ('CHECKED', 'Checked / Reviewed'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='competencyevalinternalsample',
            name='analysis_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competencyevalinternalsample',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competencyevalinternalsample',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competencyevalinternalsample',
            name='batch_lot_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='competencyevalinternalsample',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competencyevalinternalsample',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competencyevalinternalsample',
            name='exp_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competencyevalinternalsample',
            name='interpretation_of_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competencyevalinternalsample',
            name='material_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='competencyevalinternalsample',
            name='mfg_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competencyevalinternalsample',
            name='prepared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competencyevalinternalsample',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competencyevalinternalsample',
            name='reference_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='competencyevalinternalsample',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competencyevalinternalsample',
            name='result_submission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competencyevalinternalsample',
            name='source_of_material',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='competencyevalinternalsample',
            name='state_deviation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competencyevalinternalsample',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PREPARED', 'Prepared / Submitted'), ('CHECKED', 'Checked / Reviewed'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='competencyevalinternalsample',
            name='temp_rh',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='competencyevalinternalsample',
            name='unknown_sample_qty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='competencyevalinternalsample',
            name='working_standard_qty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='competencyevalptsample',
            name='analysis_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competencyevalptsample',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competencyevalptsample',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competencyevalptsample',
            name='batch_lot_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='competencyevalptsample',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competencyevalptsample',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competencyevalptsample',
            name='exp_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competencyevalptsample',
            name='interpretation_of_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competencyevalptsample',
            name='material_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='competencyevalptsample',
            name='mfg_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competencyevalptsample',
            name='prepared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competencyevalptsample',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competencyevalptsample',
            name='reference_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='competencyevalptsample',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competencyevalptsample',
            name='result_submission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competencyevalptsample',
            name='source_of_material',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='competencyevalptsample',
            name='state_deviation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competencyevalptsample',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PREPARED', 'Prepared / Submitted'), ('CHECKED', 'Checked / Reviewed'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='competencyevalptsample',
            name='temp_rh',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='competencyevalptsample',
            name='unknown_sample_qty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='competencyevalptsample',
            name='working_standard_qty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gradingmatrixdocument',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gradingmatrixdocument',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradingmatrixdocument',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gradingmatrixdocument',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradingmatrixdocument',
            name='prepared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gradingmatrixdocument',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradingmatrixdocument',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gradingmatrixdocument',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PREPARED', 'Prepared / Submitted'), ('CHECKED', 'Checked / Reviewed'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='gradingmatrixequipment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gradingmatrixequipment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradingmatrixequipment',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gradingmatrixequipment',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradingmatrixequipment',
            name='prepared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gradingmatrixequipment',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradingmatrixequipment',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gradingmatrixequipment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PREPARED', 'Prepared / Submitted'), ('CHECKED', 'Checked / Reviewed'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='gradingmatrixproduct',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gradingmatrixproduct',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradingmatrixproduct',
            name='batch_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gradingmatrixproduct',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gradingmatrixproduct',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradingmatrixproduct',
            name='dosage_form',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gradingmatrixproduct',
            name='exp_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gradingmatrixproduct',
            name='mfg_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gradingmatrixproduct',
            name='prepared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gradingmatrixproduct',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradingmatrixproduct',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gradingmatrixproduct',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gradingmatrixproduct',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PREPARED', 'Prepared / Submitted'), ('CHECKED', 'Checked / Reviewed'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='individualtrainingrecord',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individualtrainingrecord',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='individualtrainingrecord',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individualtrainingrecord',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='individualtrainingrecord',
            name='prepared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individualtrainingrecord',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='individualtrainingrecord',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PREPARED', 'Prepared / Submitted'), ('CHECKED', 'Checked / Reviewed'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='orientationplan',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orientationplan',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orientationplan',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orientationplan',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orientationplan',
            name='prepared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orientationplan',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orientationplan',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PREPARED', 'Prepared / Submitted'), ('CHECKED', 'Checked / Reviewed'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='prepared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PREPARED', 'Prepared / Submitted'), ('CHECKED', 'Checked / Reviewed'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='technicalpersonnellist',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technicalpersonnellist',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technicalpersonnellist',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='technicalpersonnellist',
            name='prepared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technicalpersonnellist',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='technicalpersonnellist',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PREPARED', 'Prepared / Submitted'), ('CHECKED', 'Checked / Reviewed'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='trainerevaluation',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainerevaluation',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainerevaluation',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainerevaluation',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainerevaluation',
            name='prepared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainerevaluation',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainerevaluation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PREPARED', 'Prepared / Submitted'), ('CHECKED', 'Checked / Reviewed'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='trainingattendancesheet',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingattendancesheet',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingattendancesheet',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingattendancesheet',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingattendancesheet',
            name='prepared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingattendancesheet',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingattendancesheet',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PREPARED', 'Prepared / Submitted'), ('CHECKED', 'Checked / Reviewed'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='trainingevaluation',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingevaluation',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingevaluation',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingevaluation',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingevaluation',
            name='prepared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingevaluation',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingevaluation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PREPARED', 'Prepared / Submitted'), ('CHECKED', 'Checked / Reviewed'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='trainingfeedback',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingfeedback',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingfeedback',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingfeedback',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingfeedback',
            name='prepared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingfeedback',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingfeedback',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PREPARED', 'Prepared / Submitted'), ('CHECKED', 'Checked / Reviewed'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='trainingneedassessment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingneedassessment',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingneedassessment',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingneedassessment',
            name='prepared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingneedassessment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PREPARED', 'Prepared / Submitted'), ('CHECKED', 'Checked / Reviewed'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='competencyevalinternalsample',
            name='evaluation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competencyevalptsample',
            name='evaluation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competencyevalptsample',
            name='pt_round_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='PTSampleTestRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_description', models.CharField(max_length=255)),
                ('assigned_value', models.CharField(blank=True, max_length=100, null=True)),
                ('report_value', models.CharField(blank=True, max_length=100, null=True)),
                ('z_score', models.CharField(blank=True, max_length=100, null=True)),
                ('nmt_2_0', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='resources.competencyevalptsample')),
            ],
        ),
        migrations.CreateModel(
            name='InternalSampleTestRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_description', models.CharField(max_length=255)),
                ('assigned_value', models.CharField(blank=True, max_length=100, null=True)),
                ('report_value', models.CharField(blank=True, max_length=100, null=True)),
                ('z_score', models.CharField(blank=True, max_length=100, null=True)),
                ('nmt_2_0', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='resources.competencyevalinternalsample')),
            ],
        ),
        migrations.CreateModel(
            name='GradingMatrixProductRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tests', models.CharField(max_length=255)),
                ('methodology', models.CharField(blank=True, max_length=255, null=True)),
                ('level_1', models.CharField(blank=True, max_length=50, null=True)),
                ('level_2', models.CharField(blank=True, max_length=50, null=True)),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='resources.gradingmatrixproduct')),
            ],
        ),
        migrations.CreateModel(
            name='GradingMatrixEquipmentRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_instrument', models.CharField(max_length=255)),
                ('level_1', models.CharField(blank=True, max_length=50, null=True)),
                ('level_2', models.CharField(blank=True, max_length=50, null=True)),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='resources.gradingmatrixequipment')),
            ],
        ),
        migrations.CreateModel(
            name='GradingMatrixDocumentRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(max_length=255)),
                ('level_1', models.CharField(blank=True, max_length=50, null=True)),
                ('level_2', models.CharField(blank=True, max_length=50, null=True)),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='resources.gradingmatrixdocument')),
            ],
        ),
    ]
