# Generated by Django 4.2.30 on 2026-10-07 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0029_remove_competencyevalinternalsample_evaluator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetencyMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prepared_at', models.DateTimeField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PREPARED', 'Prepared / Submitted'), ('CHECKED', 'Checked / Reviewed'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20)),
                ('main_functions', models.CharField(blank=True, max_length=255, null=True)),
                ('score_education', models.IntegerField(blank=True, null=True)),
                ('remarks_education', models.TextField(blank=True, null=True)),
                ('score_qualification', models.IntegerField(blank=True, null=True)),
                ('remarks_qualification', models.TextField(blank=True, null=True)),
                ('score_experience', models.IntegerField(blank=True, null=True)),
                ('remarks_experience', models.TextField(blank=True, null=True)),
                ('score_training', models.IntegerField(blank=True, null=True)),
                ('remarks_training', models.TextField(blank=True, null=True)),
                ('score_technical_knowledge', models.IntegerField(blank=True, null=True)),
                ('remarks_technical_knowledge', models.TextField(blank=True, null=True)),
                ('score_skills', models.IntegerField(blank=True, null=True)),
                ('remarks_skills', models.TextField(blank=True, null=True)),
                ('score_testing_activities', models.IntegerField(blank=True, null=True)),
                ('remarks_testing_activities', models.TextField(blank=True, null=True)),
                ('score_continuous_education', models.IntegerField(blank=True, null=True)),
                ('remarks_continuous_education', models.TextField(blank=True, null=True)),
                ('overall_score', models.IntegerField(blank=True, null=True)),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Competency Monitoring (1.04)',
                'verbose_name_plural': 'Competency Monitoring (1.04)',
            },
        ),
        migrations.RemoveField(
            model_name='analystauthorizationtestinstrument',
            name='permit',
        ),
        migrations.DeleteModel(
            name='AnalystAuthorizationProduct',
        ),
        migrations.DeleteModel(
            name='AnalystAuthorizationTestInstrument',
        ),
    ]
