# Generated by Django 4.2.30 on 2026-10-07 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0030_competencymonitoring_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personnelauthorizationpermit',
            options={'verbose_name': 'Personnel Auth Permit (1.01)', 'verbose_name_plural': 'Personnel Auth Permits (1.01)'},
        ),
        migrations.RemoveField(
            model_name='personnelauthorizationpermit',
            name='authorized_by',
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='analyzed_samples',
            field=models.BooleanField(default=False, verbose_name='Analyzed the samples'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='assigned_samples',
            field=models.BooleanField(default=False, verbose_name='Assigned the samples for testing'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='boron_analysis',
            field=models.BooleanField(default=False, verbose_name='Boron Analysis'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='calcium_test',
            field=models.BooleanField(default=False, verbose_name='Calcium test'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='cec',
            field=models.BooleanField(default=False, verbose_name='CEC'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='cleaning_inspections',
            field=models.BooleanField(default=False, verbose_name='Perform the Cleaning Inspections'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='cn_ratio',
            field=models.BooleanField(default=False, verbose_name='C/N Ratio Calculation'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='conductivity_test',
            field=models.BooleanField(default=False, verbose_name='Conductivity Test'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='control_chart',
            field=models.BooleanField(default=False, verbose_name='Prepare Control Chart'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='copper_test',
            field=models.BooleanField(default=False, verbose_name='Copper Test'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='density_test',
            field=models.BooleanField(default=False, verbose_name='Density Test'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='house_keeping',
            field=models.BooleanField(default=False, verbose_name='House Keeping'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='humic_acid_test',
            field=models.BooleanField(default=False, verbose_name='Humic Acid Test'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='ident_improvement',
            field=models.BooleanField(default=False, verbose_name='Identification of Need for improvement or Deviation'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='ident_non_conformity',
            field=models.BooleanField(default=False, verbose_name='Identification of Non-Conformity'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='intermediate_checks',
            field=models.BooleanField(default=False, verbose_name='Perform the Intermediate Checks'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='internal_auditing',
            field=models.BooleanField(default=False, verbose_name='Internal Auditing'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='loss_on_drying',
            field=models.BooleanField(default=False, verbose_name='Loss on Drying'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='loss_on_ignition',
            field=models.BooleanField(default=False, verbose_name='Loss on Ignition'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='manual_titrations',
            field=models.BooleanField(default=False, verbose_name='Manual Titrations'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='measurements_uncertainty',
            field=models.BooleanField(default=False, verbose_name='Measurements of Uncertainty'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='method_validation',
            field=models.BooleanField(default=False, verbose_name='Method Validation/Verification'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='moisture_test',
            field=models.BooleanField(default=False, verbose_name='Moisture Test'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='monitoring_env_cond',
            field=models.BooleanField(default=False, verbose_name='Monitoring Environmental Conditions'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='nitrogen_test',
            field=models.BooleanField(default=False, verbose_name='Nitrogen Test'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='op_analytical_balance',
            field=models.BooleanField(default=False, verbose_name='Operation of Analytical Balance'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='op_flame_photometer',
            field=models.BooleanField(default=False, verbose_name='Operation of Flame Photometer'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='op_furnace',
            field=models.BooleanField(default=False, verbose_name='Operation of Furnace'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='op_karl_fischer',
            field=models.BooleanField(default=False, verbose_name='Operation of Karl Fischer'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='op_kjeldhal',
            field=models.BooleanField(default=False, verbose_name="Operation of Kjeldhal's Apparatus"),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='op_ph_meter',
            field=models.BooleanField(default=False, verbose_name='Operation of pH Meter'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='op_tds_meter',
            field=models.BooleanField(default=False, verbose_name='Operation of TDS Meter'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='op_uv_vis',
            field=models.BooleanField(default=False, verbose_name='Operation of UV-Visible Spectrophotometer'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='organic_matter',
            field=models.BooleanField(default=False, verbose_name='Organic Matter'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='ph_test',
            field=models.BooleanField(default=False, verbose_name='pH Test'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='phosphorus_test',
            field=models.BooleanField(default=False, verbose_name='Phosphorus Testing'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='practical_demo',
            field=models.BooleanField(default=False, verbose_name='Practical Demonstration of Testing Parameters'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='prep_review_approved_reports',
            field=models.BooleanField(default=False, verbose_name='Preparation, Reviewing and Approved of Reports'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='prep_review_procedures',
            field=models.BooleanField(default=False, verbose_name='Preparation and Reviewing of Procedures/Other Documents'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='prep_review_release_slip',
            field=models.BooleanField(default=False, verbose_name='Preparation and Review/Verify the Release slip'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='prep_temp_charts',
            field=models.BooleanField(default=False, verbose_name='Prepare the temperature/humidity charts'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='preparing_review_reports',
            field=models.BooleanField(default=False, verbose_name='Preparing/Review the Analysis Reports'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='pt_samples',
            field=models.BooleanField(default=False, verbose_name='PT Samples/Blind Samples'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='release_slip_prep',
            field=models.BooleanField(default=False, verbose_name='Release Slip Preparation'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='report_preparation',
            field=models.BooleanField(default=False, verbose_name='Report Preparation'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='review_analysis_reports',
            field=models.BooleanField(default=False, verbose_name='Review the Analysis Reports'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='sample_discard',
            field=models.BooleanField(default=False, verbose_name='Sample Discard/Dispose'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='sample_handling',
            field=models.BooleanField(default=False, verbose_name='Sample Handling'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='sample_receiving',
            field=models.BooleanField(default=False, verbose_name='Sample Receiving'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='sample_retaining',
            field=models.BooleanField(default=False, verbose_name='Sample Retaining'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='sieve_test',
            field=models.BooleanField(default=False, verbose_name='Sieve Test'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='sodium_test',
            field=models.BooleanField(default=False, verbose_name='Sodium Test'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='solution_prep',
            field=models.BooleanField(default=False, verbose_name='Solution Preparation'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='standardization',
            field=models.BooleanField(default=False, verbose_name='Standardization'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='stock_management',
            field=models.BooleanField(default=False, verbose_name='Stock Management'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='sulfur_test',
            field=models.BooleanField(default=False, verbose_name='Sulfur/Sulfate Test'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='tds_test',
            field=models.BooleanField(default=False, verbose_name='TDS Test'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='total_organic_carbon',
            field=models.BooleanField(default=False, verbose_name='Total Organic Carbon'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='training_lms',
            field=models.BooleanField(default=False, verbose_name='Training of Lab Staff on LMS 17025:2017'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='weighing',
            field=models.BooleanField(default=False, verbose_name='Weighing'),
        ),
        migrations.AddField(
            model_name='personnelauthorizationpermit',
            name='zinc_test',
            field=models.BooleanField(default=False, verbose_name='Zinc Test'),
        ),
        migrations.AlterField(
            model_name='personnelauthorizationpermit',
            name='analyst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personnelauthorizationpermit',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
