# Generated by Django 4.2.30 on 2026-10-07 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0031_alter_personnelauthorizationpermit_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewInductionOrientation_2_11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prepared_at', models.DateTimeField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PREPARED', 'Prepared / Submitted'), ('CHECKED', 'Checked / Reviewed'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20)),
                ('candidate_name', models.CharField(max_length=255)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('orientation_started_from', models.DateField(blank=True, null=True)),
                ('probation_period', models.CharField(blank=True, max_length=100, null=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'New Induction Orientation (2.11)',
                'verbose_name_plural': 'New Induction Orientations (2.11)',
            },
        ),
        migrations.CreateModel(
            name='InductionOrientationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsibility', models.CharField(max_length=255)),
                ('trainer', models.CharField(max_length=255)),
                ('training_duration', models.CharField(max_length=100)),
                ('orientation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='resources.newinductionorientation_2_11')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorizedPersonnelList_2_06',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prepared_at', models.DateTimeField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PREPARED', 'Prepared / Submitted'), ('CHECKED', 'Checked / Reviewed'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20)),
                ('date_issued', models.DateField()),
                ('revision_number', models.CharField(max_length=50)),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='master_lists/2_06/')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Authorized Personnel List (2.06)',
                'verbose_name_plural': 'Authorized Personnel Lists (2.06)',
            },
        ),
    ]
