# Generated by Django 4.2.30 on 2026-10-07 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0034_comparativestatement_6_05_crmlist_5_01_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterListDocument_7_01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prepared_at', models.DateTimeField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PREPARED', 'Prepared / Submitted'), ('CHECKED', 'Checked / Reviewed'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20)),
                ('description', models.CharField(default='Master List of Documents', max_length=255)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Master List of Document (7.01)',
                'verbose_name_plural': 'Master List of Documents (7.01)',
            },
        ),
        migrations.CreateModel(
            name='MasterListDocumentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_code', models.CharField(max_length=150)),
                ('document_title', models.CharField(max_length=255)),
                ('file_code', models.CharField(blank=True, max_length=150, null=True)),
                ('file_location', models.CharField(blank=True, max_length=255, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('rev_no', models.CharField(blank=True, max_length=50, null=True)),
                ('keeper_1', models.CharField(blank=True, max_length=150, null=True)),
                ('keeper_2', models.CharField(blank=True, max_length=150, null=True)),
                ('keeper_3', models.CharField(blank=True, max_length=150, null=True)),
                ('master_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='resources.masterlistdocument_7_01')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentChangeRequest_7_02',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prepared_at', models.DateTimeField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PREPARED', 'Prepared / Submitted'), ('CHECKED', 'Checked / Reviewed'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20)),
                ('dcr_no', models.CharField(max_length=100)),
                ('dcr_date', models.DateField()),
                ('request_raised_by', models.CharField(max_length=150)),
                ('section', models.CharField(max_length=150)),
                ('document_title', models.CharField(max_length=255)),
                ('document_status', models.CharField(choices=[('NEW', 'NEW'), ('EXISTING', 'EXISTING')], max_length=50)),
                ('reason', models.CharField(choices=[('New Process Documentation', 'New Process Documentation'), ('New Form Documentation', 'New Form Documentation'), ('Addition in Document', 'Addition in Document'), ('Correction in Document', 'Correction in Document'), ('Deletion within Document', 'Deletion within Document'), ('Modification in Document', 'Modification in Document')], max_length=150)),
                ('description_of_requirement', models.TextField(blank=True, null=True)),
                ('effected_sections', models.TextField(blank=True, help_text='Not Applicable on New Documents', null=True)),
                ('review_by', models.CharField(blank=True, max_length=150, null=True)),
                ('designation', models.CharField(blank=True, max_length=150, null=True)),
                ('review_status', models.CharField(blank=True, choices=[('Draft Reviewed', 'Draft Reviewed'), ('Draft Rejected', 'Draft Rejected'), ('Draft Revision Suggested', 'Draft Revision Suggested')], max_length=100, null=True)),
                ('reason_for_rejection', models.CharField(blank=True, choices=[('Conflict with Policy', 'Conflict with Policy'), ('Conflict with Procedure', 'Conflict with Procedure'), ('Conflict with Client Requirement', 'Conflict with Client Requirement'), ('Conflict with Regulation', 'Conflict with Regulation'), ('Incorrect Draft', 'Incorrect Draft'), ('Draft Does not reflect "Description of Requirement"', 'Draft Does not reflect "Description of Requirement"')], max_length=150, null=True)),
                ('final_remarks', models.TextField(blank=True, null=True)),
                ('submitted_for_final_approval_on', models.DateField(blank=True, null=True)),
                ('approved_by_name', models.CharField(blank=True, max_length=150, null=True)),
                ('approved_designation', models.CharField(blank=True, max_length=150, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Change Request (7.02)',
                'verbose_name_plural': 'Document Change Requests (7.02)',
            },
        ),
    ]
