# Generated by Django 4.2.30 on 2026-10-07 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0038_analyticalbalancecheck_17_08_annualqaprogram_17_07_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityObjectiveForm_18_01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prepared_at', models.DateTimeField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PREPARED', 'Prepared / Submitted'), ('CHECKED', 'Checked / Reviewed'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20)),
                ('year', models.CharField(max_length=50)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quality Objective Form (18.01)',
                'verbose_name_plural': 'Quality Objective Forms (18.01)',
            },
        ),
        migrations.CreateModel(
            name='QualityObjectiveProgramStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective_sn', models.IntegerField(help_text='SN of the Objective this step belongs to')),
                ('step_no', models.IntegerField()),
                ('particulars', models.CharField(max_length=255)),
                ('responsibility', models.CharField(max_length=150)),
                ('target_date', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_steps', to='resources.qualityobjectiveform_18_01')),
            ],
        ),
        migrations.CreateModel(
            name='QualityObjectiveItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.IntegerField()),
                ('quality_objective', models.CharField(max_length=255)),
                ('target_date', models.CharField(max_length=100)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='resources.qualityobjectiveform_18_01')),
            ],
        ),
    ]
